In [1]:
#Project 2 Lede Program
#Marcela Vilar Mota Santos

In [1]:
import pandas as pd
from dotenv import load_dotenv
import os
import geocoder

## cleaning

In [3]:
df_laguardia = pd.read_csv('df_laguardia.csv')
df_laguardia.head(5)

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,ar_time
0,1780793531,2026-06-06 20:52,KDEN,SWA4480,KLGA,1780804798,2026-06-06 23:59,2026-06-06,23:59
1,1780797756,2026-06-06 22:02,KBNA,SWA2144,KLGA,1780804585,2026-06-06 23:56,2026-06-06,23:56
2,1780802023,2026-06-06 23:13,KBWI,DAL997,KLGA,1780804357,2026-06-06 23:52,2026-06-06,23:52
3,1780793350,2026-06-06 20:49,KDAL,SWA3256,KLGA,1780803735,2026-06-06 23:42,2026-06-06,23:42
4,1780796317,2026-06-06 21:38,KSTL,SWA4684,KLGA,1780803608,2026-06-06 23:40,2026-06-06,23:40

In [4]:
df_laguardia.shape

(14582, 9)

In [5]:
df_laguardia.sort_values("arrival_conv", ascending = True)
#first flight la guardia 2026-06-06	06:51

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,ar_time
321,1780741010,2026-06-06 06:16,KSYR,EDV5355,KLGA,1780743084,2026-06-06 06:51,2026-06-06,06:51
320,1780741057,2026-06-06 06:17,KROC,EDV5311,KLGA,1780743687,2026-06-06 07:01,2026-06-06,07:01
319,1780740944,2026-06-06 06:15,KBUF,RPA5842,KLGA,1780743914,2026-06-06 07:05,2026-06-06,07:05
318,1780742442,2026-06-06 06:40,KALB,EDV5454,KLGA,1780744043,2026-06-06 07:07,2026-06-06,07:07
317,1780740120,2026-06-06 06:02,CYYZ,EDV5183,KLGA,1780744164,2026-06-06 07:09,2026-06-06,07:09
...,...,...,...,...,...,...,...,...,...
14181,1783298443,2026-07-05 20:40,KBGR,RPA4348,KLGA,1783305792,2026-07-05 22:43,2026-07-05,22:43
14180,1783296921,2026-07-05 20:15,KFLL,DAL2321,KLGA,1783306248,2026-07-05 22:50,2026-07-05,22:50
14179,1783296861,2026-07-05 20:14,KMIA,DAL2300,KLGA,1783306631,2026-07-05 22:57,2026-07-05,22:57
14178,1783298003,2026-07-05 20:33,KMCO,DAL2520,KLGA,1783307478,2026-07-05 23:11,2026-07-05,23:11
14177,1783296112,2026-07-05 20:01,KMCO,JBU798,KLGA,1783307750,2026-07-05 23:15,2026-07-05,23:15

In [6]:
df_laguardia = df_laguardia.rename(columns ={"ar_time" : "time"})
df_laguardia

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time
0,1780793531,2026-06-06 20:52,KDEN,SWA4480,KLGA,1780804798,2026-06-06 23:59,2026-06-06,23:59
1,1780797756,2026-06-06 22:02,KBNA,SWA2144,KLGA,1780804585,2026-06-06 23:56,2026-06-06,23:56
2,1780802023,2026-06-06 23:13,KBWI,DAL997,KLGA,1780804357,2026-06-06 23:52,2026-06-06,23:52
3,1780793350,2026-06-06 20:49,KDAL,SWA3256,KLGA,1780803735,2026-06-06 23:42,2026-06-06,23:42
4,1780796317,2026-06-06 21:38,KSTL,SWA4684,KLGA,1780803608,2026-06-06 23:40,2026-06-06,23:40
...,...,...,...,...,...,...,...,...,...
14577,1783222721,2026-07-04 23:38,KORD,AAL2086,KLGA,1783228818,2026-07-05 01:20,2026-07-05,01:20
14578,1783222641,2026-07-04 23:37,KCMH,RPA5784,KLGA,1783227896,2026-07-05 01:04,2026-07-05,01:04
14579,1783213820,2026-07-04 21:10,KDFW,AAL2708,KLGA,1783225456,2026-07-05 00:24,2026-07-05,00:24
14580,1783223125,2026-07-04 23:45,KALB,SWA2144,KLGA,1783224929,2026-07-05 00:15,2026-07-05,00:15
14581,1783212557,2026-07-04 20:49,KMCO,JBU798,KLGA,1783224193,2026-07-05 00:03,2026-07-05,00:03

In [7]:
df_laguardia["arr_airport"].unique()

<ArrowStringArray>
['KLGA']
Length: 1, dtype: str

In [8]:
df_laguardia["dep_airport"].unique()

<ArrowStringArray>
['KDEN', 'KBNA', 'KBWI', 'KDAL', 'KSTL', 'KBOS', 'KDFW', 'KMSP', 'KMSY',
 'KDTW',
 ...
 'KLAF', 'KBFI', 'KILG', 'XS25', 'KPNE', 'KGKY', '06MO', 'KADW', 'EDSB',
 'KNEW']
Length: 256, dtype: str

In [9]:
df_laguardia[(df_laguardia["dep_airport"] == "KJFK") |
            (df_laguardia["dep_airport"] == "KEWR")]

#first result N347MT is a helicopter
#the dep_airport was Staten Island University Hospital (NY52)

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time
196,1780762693,2026-06-06 12:18,KEWR,N347MT,KLGA,1780763398,2026-06-06 12:29,2026-06-06,12:29
205,1780761069,2026-06-06 11:51,KJFK,DAL9963,KLGA,1780761769,2026-06-06 12:02,2026-06-06,12:02
225,1780757760,2026-06-06 10:56,KJFK,N918PD,KLGA,1780758501,2026-06-06 11:08,2026-06-06,11:08
1016,1780944723,2026-06-08 14:52,KEWR,N747EE,KLGA,1780951733,2026-06-08 16:48,2026-06-08,16:48
1041,1780947968,2026-06-08 15:46,KJFK,RPA9931,KLGA,1780948909,2026-06-08 16:01,2026-06-08,16:01
1254,1780924411,2026-06-08 09:13,KJFK,N777ZA,KLGA,1780925805,2026-06-08 09:36,2026-06-08,09:36
1615,1781034360,2026-06-09 15:46,KJFK,N38BL,KLGA,1781035462,2026-06-09 16:04,2026-06-09,16:04
2472,1781213103,2026-06-11 17:25,KEWR,N35HF,KLGA,1781219810,2026-06-11 19:16,2026-06-11,19:16
2566,1781203759,2026-06-11 14:49,KEWR,N84BL,KLGA,1781206738,2026-06-11 15:38,2026-06-11,15:38
2744,1781186516,2026-06-11 10:01,KJFK,DAL9963,KLGA,1781187264,2026-06-11 10:14,2026-06-11,10:14
2804,1781179849,2026-06-11 08:10,KJFK,RPA9928,KLGA,1781180591,2026-06-11 08:23,2026-06-11,08:23
2844,1781174615,2026-06-11 06:43,KEWR,UAL3925,KLGA,1781175595,2026-06-11 06:59,2026-06-11,06:59
2850,1781172637,2026-06-11 06:10,KEWR,UAL3930,KLGA,1781173422,2026-06-11 06:23,2026-06-11,06:23
2960,1781291892,2026-06-12 15:18,KEWR,N551HY,KLGA,1781297452,2026-06-12 16:50,2026-06-12,16:50
3150,1781272662,2026-06-12 09:57,KEWR,UAL3907,KLGA,1781273333,2026-06-12 10:08,2026-06-12,10:08
3590,1781348956,2026-06-13 07:09,KJFK,AAL1329,KLGA,1781350016,2026-06-13 07:26,2026-06-13,07:26
3598,1781343600,2026-06-13 05:40,KEWR,N456MT,KLGA,1781344228,2026-06-13 05:50,2026-06-13,05:50
3735,1781472390,2026-06-14 17:26,KEWR,N347MT,KLGA,1781473049,2026-06-14 17:37,2026-06-14,17:37
3942,1781447375,2026-06-14 10:29,KJFK,AAL968P,KLGA,1781448255,2026-06-14 10:44,2026-06-14,10:44
4191,1781562349,2026-06-15 18:25,KJFK,N918PD,KLGA,1781563157,2026-06-15 18:39,2026-06-15,18:39
4215,1781555829,2026-06-15 16:37,KEWR,N945RF,KLGA,1781560249,2026-06-15 17:50,2026-06-15,17:50
4465,1781531073,2026-06-15 09:44,KEWR,N92N,KLGA,1781532138,2026-06-15 10:02,2026-06-15,10:02
4564,1781504231,2026-06-15 02:17,KJFK,JBU572,KLGA,1781505145,2026-06-15 02:32,2026-06-15,02:32
4758,1781645102,2026-06-16 17:25,KJFK,N62ZA,KLGA,1781646114,2026-06-16 17:41,2026-06-16,17:41
5190,1781744232,2026-06-17 20:57,KJFK,RPA5694,KLGA,1781745617,2026-06-17 21:20,2026-06-17,21:20
5305,1781730690,2026-06-17 17:11,KJFK,N408GG,KLGA,1781731632,2026-06-17 17:27,2026-06-17,17:27
5874,1781809936,2026-06-18 15:12,KEWR,N35HF,KLGA,1781815961,2026-06-18 16:52,2026-06-18,16:52
5911,1781811227,2026-06-18 15:33,KEWR,N777ZA,KLGA,1781812012,2026-06-18 15:46,2026-06-18,15:46
6098,1781789723,2026-06-18 09:35,KEWR,N92N,KLGA,1781791300,2026-06-18 10:01,2026-06-18,10:01
6154,1781782817,2026-06-18 07:40,KEWR,N38BL,KLGA,1781785528,2026-06-18 08:25,2026-06-18,08:25
6335,1781911385,2026-06-19 19:23,KJFK,N27M,KLGA,1781913649,2026-06-19 20:00,2026-06-19,20:00
6408,1781894988,2026-06-19 14:49,KJFK,RPA4734,KLGA,1781906083,2026-06-19 17:54,2026-06-19,17:54
7280,1782084290,2026-06-21 19:24,KJFK,N777ZA,KLGA,1782085019,2026-06-21 19:36,2026-06-21,19:36
7563,1782054524,2026-06-21 11:08,KJFK,AAL229G,KLGA,1782055461,2026-06-21 11:24,2026-06-21,11:24
7635,1782046002,2026-06-21 08:46,KJFK,AAL54R,KLGA,1782046887,2026-06-21 09:01,2026-06-21,09:01
7730,1782176741,2026-06-22 21:05,KJFK,AAL3050,KLGA,1782177732,2026-06-22 21:22,2026-06-22,21:22
8001,1782126799,2026-06-22 07:13,KEWR,N38HF,KLGA,1782131986,2026-06-22 08:39,2026-06-22,08:39
8226,1782255067,2026-06-23 18:51,KJFK,AAL1015,KLGA,1782256122,2026-06-23 19:08,2026-06-23,19:08
8537,1782212473,2026-06-23 07:01,KJFK,RPA9930,KLGA,1782213408,2026-06-23 07:16,2026-06-23,07:16
8539,1782212329,2026-06-23 06:58,KJFK,RPA9929,KLGA,1782213225,2026-06-23 07:13,2026-06-23,07:13
10116,1782488176,2026-06-26 11:36,KEWR,FXC22,KLGA,1782495073,2026-06-26 13:31,2026-06-26,13:31
10944,1782676592,2026-06-28 15:56,KJFK,GPD828,KLGA,1782677669,2026-06-28 16:14,2026-06-28,16:14
11229,1782640989,2026-06-28 06:03,KJFK,JBU8400,KLGA,1782641869,2026-06-28 06:17,2026-06-28,06:17
11399,1782769967,2026-06-29 17:52,KJFK,N777ZA,KLGA,1782770607,2026-06-29 18:03,2026-06-29,18:03
11443,1782763980,2026-06-29 16:13,KEWR,N27M,KLGA,1782765478,2026-06-29 16:37,2026-06-29,16:37
11636,1782744005,2026-06-29 10:40,KJFK,DAL9963,KLGA,1782744715,2026-06-29 10:51,2026-06-29,10:51
11690,1782738930,2026-06-29 09:15,KJFK,RPA4470,KLGA,1782739661,2026-06-29 09:27,2026-06-29,09:27
12523,1782937243,2026-07-01 16:20,KEWR,N945RF,KLGA,1782937918,2026-07-01 16:31,2026-07-01,16:31
13090,1783019982,2026-07-02 15:19,KJFK,N84BL,KLGA,1783021497,2026-07-02 15:44,2026-07-02,15:44
13264,1783003419,2026-07-02 10:43,KJFK,N726SH,KLGA,1783004203,2026-07-02 10:56,2026-07-02,10:56
14475,1783260422,2026-07-05 10:07,KEWR,UAL3883,KLGA,1783262036,2026-07-05 10:33,2026-07-05,10:33

In [10]:
(df_laguardia[(df_laguardia["dep_airport"] == "KJFK") |
            (df_laguardia["dep_airport"] == "KEWR")]).count()

#51 flights

dep_unix        51
dep_conv        51
dep_airport     51
callsign        51
arr_airport     51
arrival_unix    51
arrival_conv    51
arrival         51
time            51
dtype: int64

In [11]:
df_jfk = pd.read_csv('df_jfk.csv')
df_jfk.head(5)

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time
0,1780787746,2026-06-06 19:15,NaN,BWA526,KJFK,1780804781,2026-06-06 23:59,2026-06-06,23:59
1,1780795969,2026-06-06 21:32,KFLL,DAL1419,KJFK,1780804705,2026-06-06 23:58,2026-06-06,23:58
2,1780776012,2026-06-06 16:00,NaN,JBU36,KJFK,1780804617,2026-06-06 23:56,2026-06-06,23:56
3,1780801713,2026-06-06 23:08,KBOS,KAL085,KJFK,1780804558,2026-06-06 23:55,2026-06-06,23:55
4,1780800705,2026-06-06 22:51,KBUF,EDV5250,KJFK,1780804403,2026-06-06 23:53,2026-06-06,23:53

In [12]:
df_jfk.shape

(19660, 9)

In [13]:
df_jfk.sort_values("arrival_conv", ascending = True)
#first flight jfk 2026-06-06	00:17

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time
554,1780716712,2026-06-05 23:31,NaN,JBU210,KJFK,1780719476,2026-06-06 00:17,2026-06-06,00:17
553,1780701412,2026-06-05 19:16,KSFO,DAL363,KJFK,1780719621,2026-06-06 00:20,2026-06-06,00:20
552,1780701868,2026-06-05 19:24,KLAX,JBU824,KJFK,1780719789,2026-06-06 00:23,2026-06-06,00:23
551,1780703237,2026-06-05 19:47,KSEA,DAL722,KJFK,1780720073,2026-06-06 00:27,2026-06-06,00:27
550,1780706425,2026-06-05 20:40,NaN,GLG7396,KJFK,1780720316,2026-06-06 00:31,2026-06-06,00:31
...,...,...,...,...,...,...,...,...,...
19054,1783288946,2026-07-05 18:02,KLAX,JBU624,KJFK,1783308569,2026-07-05 23:29,2026-07-05,23:29
19053,1783288417,2026-07-05 17:53,KSFO,JBU416,KJFK,1783308735,2026-07-05 23:32,2026-07-05,23:32
19052,1783296349,2026-07-05 20:05,KAUS,DAL1643,KJFK,1783308896,2026-07-05 23:34,2026-07-05,23:34
19051,1783291859,2026-07-05 18:50,NaN,BWA526,KJFK,1783309039,2026-07-05 23:37,2026-07-05,23:37
19050,1783252791,2026-07-05 07:59,SABE,LNE1454,KJFK,1783309229,2026-07-05 23:40,2026-07-05,23:40

In [14]:
df_jfk["arr_airport"].unique()

<ArrowStringArray>
['KJFK']
Length: 1, dtype: str

In [15]:
df_jfk["dep_airport"].unique()

<ArrowStringArray>
[   nan, 'KFLL', 'KBOS', 'KBUF', 'KMCO', 'KCHS', 'KSFO', 'KSLC', 'KLAX',
 'KORD',
 ...
 'TLPL', 'KDYL', '14NK', 'KGAI', 'LIRP', 'SUBL', 'KN82', 'KPKB', 'KLKP',
 'KFWQ']
Length: 357, dtype: str

In [16]:
df_jfk[(df_jfk["dep_airport"] == "KLGA") |
            (df_jfk["dep_airport"] == "KEWR")]

#first result N347MT is a helicopter
#the dep_airport was Staten Island University Hospital (NY52)

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time
690,1780875531,2026-06-07 19:38,KEWR,N27M,KJFK,1780876589,2026-06-07 19:56,2026-06-07,19:56
749,1780870302,2026-06-07 18:11,KEWR,N38BL,KJFK,1780871746,2026-06-07 18:35,2026-06-07,18:35
1485,1780947060,2026-06-08 15:31,KEWR,N403TD,KJFK,1780950444,2026-06-08 16:27,2026-06-08,16:27
1510,1780944932,2026-06-08 14:55,KEWR,N84BL,KJFK,1780948289,2026-06-08 15:51,2026-06-08,15:51
1639,1780937660,2026-06-08 12:54,KEWR,N38BL,KJFK,1780938876,2026-06-08 13:14,2026-06-08,13:14
...,...,...,...,...,...,...,...,...,...
18811,1783180863,2026-07-04 12:01,KEWR,MARINE2,KJFK,1783182253,2026-07-04 12:24,2026-07-04,12:24
18849,1783172743,2026-07-04 09:45,KEWR,CHRGR06,KJFK,1783176202,2026-07-04 10:43,2026-07-04,10:43
19370,1783270147,2026-07-05 12:49,KEWR,N69F,KJFK,1783273204,2026-07-05 13:40,2026-07-05,13:40
19508,1783253935,2026-07-05 08:18,KEWR,UPS5051,KJFK,1783255407,2026-07-05 08:43,2026-07-05,08:43
19611,1783231996,2026-07-05 02:13,KEWR,AMX406,KJFK,1783233177,2026-07-05 02:32,2026-07-05,02:32

In [17]:
df_newark = pd.read_csv('df_newark.csv')
df_newark.head(5)

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time
0,1.780799e+09,2026-06-06 22:21,KCLT,AAL2794,KEWR,1780804791,2026-06-06 23:59,2026-06-06,23:59
1,1.780794e+09,2026-06-06 21:07,KPBI,UAL1187,KEWR,1780804649,2026-06-06 23:57,2026-06-06,23:57
2,1.780788e+09,2026-06-06 19:17,KSEA,ASA293,KEWR,1780804527,2026-06-06 23:55,2026-06-06,23:55
3,1.780789e+09,2026-06-06 19:37,NaN,UAL1446,KEWR,1780804409,2026-06-06 23:53,2026-06-06,23:53
4,1.780796e+09,2026-06-06 21:36,KATL,RPA3402,KEWR,1780804307,2026-06-06 23:51,2026-06-06,23:51

In [18]:
df_newark["arr_airport"].unique()

<ArrowStringArray>
['KEWR']
Length: 1, dtype: str

In [19]:
df_newark.sort_values("arrival_conv", ascending = True)
#first flight newark 2026-06-06	00:01

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time
506,1.780708e+09,2026-06-05 21:06,KIAH,UAL8244,KEWR,1780718466,2026-06-06 00:01,2026-06-06,00:01
505,1.780703e+09,2026-06-05 19:39,KSEA,ASA293,KEWR,1780718636,2026-06-06 00:03,2026-06-06,00:03
504,1.780711e+09,2026-06-05 21:57,KMSP,DAL2846,KEWR,1780718810,2026-06-06 00:06,2026-06-06,00:06
503,1.780703e+09,2026-06-05 19:35,KLAX,UAL1700,KEWR,1780718984,2026-06-06 00:09,2026-06-06,00:09
502,1.780714e+09,2026-06-05 22:44,KATL,FFT4602,KEWR,1780719809,2026-06-06 00:23,2026-06-06,00:23
...,...,...,...,...,...,...,...,...,...
18420,1.783291e+09,2026-07-05 18:37,MMMX,AMX410,KEWR,1783308509,2026-07-05 23:28,2026-07-05,23:28
18419,1.783291e+09,2026-07-05 18:34,KSNA,UAL1559,KEWR,1783308772,2026-07-05 23:32,2026-07-05,23:32
18418,1.783296e+09,2026-07-05 20:07,MMUN,UAL1047,KEWR,1783309073,2026-07-05 23:37,2026-07-05,23:37
18417,1.783300e+09,2026-07-05 20:58,KDFW,UAL402,KEWR,1783309813,2026-07-05 23:50,2026-07-05,23:50
18416,1.783285e+09,2026-07-05 17:02,TJSJ,JBU894,KEWR,1783310238,2026-07-05 23:57,2026-07-05,23:57

In [20]:
df = pd.concat([df_jfk, df_laguardia, df_newark], ignore_index=True)

In [21]:
df.shape

(53224, 9)

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53224 entries, 0 to 53223
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   dep_unix      53217 non-null  float64
 1   dep_conv      53217 non-null  str
 2   dep_airport   48485 non-null  str
 3   callsign      53220 non-null  str
 4   arr_airport   53224 non-null  str
 5   arrival_unix  53224 non-null  int64
 6   arrival_conv  53224 non-null  str
 7   arrival       53224 non-null  str
 8   time          53224 non-null  str
dtypes: float64(1), int64(1), str(7)
memory usage: 6.8 MB

In [23]:
df.head(5)

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time
0,1.780788e+09,2026-06-06 19:15,NaN,BWA526,KJFK,1780804781,2026-06-06 23:59,2026-06-06,23:59
1,1.780796e+09,2026-06-06 21:32,KFLL,DAL1419,KJFK,1780804705,2026-06-06 23:58,2026-06-06,23:58
2,1.780776e+09,2026-06-06 16:00,NaN,JBU36,KJFK,1780804617,2026-06-06 23:56,2026-06-06,23:56
3,1.780802e+09,2026-06-06 23:08,KBOS,KAL085,KJFK,1780804558,2026-06-06 23:55,2026-06-06,23:55
4,1.780801e+09,2026-06-06 22:51,KBUF,EDV5250,KJFK,1780804403,2026-06-06 23:53,2026-06-06,23:53

In [24]:
df["dep_airport"].isna().sum()
#no data from some departure airports

np.int64(4739)

In [25]:
df.isna().sum()

dep_unix           7
dep_conv           7
dep_airport     4739
callsign           4
arr_airport        0
arrival_unix       0
arrival_conv       0
arrival            0
time               0
dtype: int64

In [26]:
df[df["dep_unix"].isna()]
#null values
#7 lines

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time
37986,NaN,NaN,NaN,UAL146,KEWR,1781317098,2026-06-12 22:18,2026-06-12,22:18
42465,NaN,NaN,NaN,UAL940,KEWR,1781918509,2026-06-19 21:21,2026-06-19,21:21
45750,NaN,NaN,NaN,UAL956,KEWR,1782337517,2026-06-24 17:45,2026-06-24,17:45
46327,NaN,NaN,NaN,UAL966,KEWR,1782434625,2026-06-25 20:43,2026-06-25,20:43
50296,NaN,NaN,NaN,UAL36,KEWR,1782951927,2026-07-01 20:25,2026-07-01,20:25
51639,NaN,NaN,NaN,UAL272,KEWR,1783130662,2026-07-03 22:04,2026-07-03,22:04
51749,NaN,NaN,NaN,UAL380,KEWR,1783111870,2026-07-03 16:51,2026-07-03,16:51

In [27]:
df.sort_values("arrival_conv", ascending = True)

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time
34748,1.780708e+09,2026-06-05 21:06,KIAH,UAL8244,KEWR,1780718466,2026-06-06 00:01,2026-06-06,00:01
34747,1.780703e+09,2026-06-05 19:39,KSEA,ASA293,KEWR,1780718636,2026-06-06 00:03,2026-06-06,00:03
34746,1.780711e+09,2026-06-05 21:57,KMSP,DAL2846,KEWR,1780718810,2026-06-06 00:06,2026-06-06,00:06
34745,1.780703e+09,2026-06-05 19:35,KLAX,UAL1700,KEWR,1780718984,2026-06-06 00:09,2026-06-06,00:09
554,1.780717e+09,2026-06-05 23:31,NaN,JBU210,KJFK,1780719476,2026-06-06 00:17,2026-06-06,00:17
...,...,...,...,...,...,...,...,...,...
19051,1.783292e+09,2026-07-05 18:50,NaN,BWA526,KJFK,1783309039,2026-07-05 23:37,2026-07-05,23:37
52660,1.783296e+09,2026-07-05 20:07,MMUN,UAL1047,KEWR,1783309073,2026-07-05 23:37,2026-07-05,23:37
19050,1.783253e+09,2026-07-05 07:59,SABE,LNE1454,KJFK,1783309229,2026-07-05 23:40,2026-07-05,23:40
52659,1.783300e+09,2026-07-05 20:58,KDFW,UAL402,KEWR,1783309813,2026-07-05 23:50,2026-07-05,23:50
52658,1.783285e+09,2026-07-05 17:02,TJSJ,JBU894,KEWR,1783310238,2026-07-05 23:57,2026-07-05,23:57

In [28]:
df_KEWR_KEWR = df[(df["arr_airport"] == "KEWR") & (df["dep_airport"] == "KEWR")]
df_KEWR_KEWR
#N27M is a helicopter
#mostly helicopters

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time
34334,1.780753e+09,2026-06-06 09:31,KEWR,UAL1560,KEWR,1780794376,2026-06-06 21:06,2026-06-06,21:06
34344,1.780786e+09,2026-06-06 18:46,KEWR,N207MH,KEWR,1780787743,2026-06-06 19:15,2026-06-06,19:15
34345,1.780752e+09,2026-06-06 09:26,KEWR,UAL614,KEWR,1780787487,2026-06-06 19:11,2026-06-06,19:11
34350,1.780786e+09,2026-06-06 18:45,KEWR,N401FN,KEWR,1780786960,2026-06-06 19:02,2026-06-06,19:02
34352,1.780786e+09,2026-06-06 18:44,KEWR,N4846,KEWR,1780786890,2026-06-06 19:01,2026-06-06,19:01
...,...,...,...,...,...,...,...,...,...
53071,1.783261e+09,2026-07-05 10:15,KEWR,N4846,KEWR,1783261888,2026-07-05 10:31,2026-07-05,10:31
53084,1.783258e+09,2026-07-05 09:26,KEWR,N401FN,KEWR,1783259684,2026-07-05 09:54,2026-07-05,09:54
53085,1.783214e+09,2026-07-04 21:09,KEWR,UAL1472,KEWR,1783259599,2026-07-05 09:53,2026-07-05,09:53
53086,1.783258e+09,2026-07-05 09:22,KEWR,N207MH,KEWR,1783259542,2026-07-05 09:52,2026-07-05,09:52
53147,1.783249e+09,2026-07-05 06:52,KEWR,N27M,KEWR,1783250541,2026-07-05 07:22,2026-07-05,07:22

In [29]:
#droping those in the original database
df = df[~((df["arr_airport"] == "KEWR") & (df["dep_airport"] == "KEWR"))]

In [30]:
df.shape

(51306, 9)

In [31]:
df_jfk_jfk = df[(df["arr_airport"] == "KJFK") & (df["dep_airport"] == "KJFK")]
df_jfk_jfk

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time
69,1.780754e+09,2026-06-06 09:58,KJFK,JBU1532,KJFK,1780796807,2026-06-06 21:46,2026-06-06,21:46
70,1.780760e+09,2026-06-06 11:38,KJFK,JBU158,KJFK,1780796634,2026-06-06 21:43,2026-06-06,21:43
80,1.780763e+09,2026-06-06 12:18,KJFK,JBU1088,KJFK,1780795332,2026-06-06 21:22,2026-06-06,21:22
89,1.780763e+09,2026-06-06 12:25,KJFK,JBU1052,KJFK,1780793878,2026-06-06 20:57,2026-06-06,20:57
111,1.780753e+09,2026-06-06 09:37,KJFK,JBU57,KJFK,1780788872,2026-06-06 19:34,2026-06-06,19:34
...,...,...,...,...,...,...,...,...,...
19572,1.783242e+09,2026-07-05 04:54,KJFK,FYNST21,KJFK,1783243600,2026-07-05 05:26,2026-07-05,05:26
19585,1.783239e+09,2026-07-05 04:14,KJFK,N917PD,KJFK,1783241067,2026-07-05 04:44,2026-07-05,04:44
19591,1.783238e+09,2026-07-05 03:51,KJFK,N31419,KJFK,1783239705,2026-07-05 04:21,2026-07-05,04:21
19634,1.783228e+09,2026-07-05 01:12,KJFK,N917PD,KJFK,1783230419,2026-07-05 01:46,2026-07-05,01:46
19658,1.783191e+09,2026-07-04 14:50,KJFK,JBU1112,KJFK,1783226540,2026-07-05 00:42,2026-07-05,00:42

In [32]:
df = df[~((df["arr_airport"] == "KJFK") & (df["dep_airport"] == "KJFK"))]
#droping those

In [33]:
df.shape

(50719, 9)

In [34]:
df_lgalga = df[(df["arr_airport"] == "KLGA") & (df["dep_airport"] == "KLGA")]
df_lgalga

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time
19711,1.780767e+09,2026-06-06 13:23,KLGA,RPA4475,KLGA,1780788454,2026-06-06 19:27,2026-06-06,19:27
19771,1.780762e+09,2026-06-06 11:59,KLGA,EDV5438,KLGA,1780780019,2026-06-06 17:06,2026-06-06,17:06
22616,1.781293e+09,2026-06-12 15:33,KLGA,N1308,KLGA,1781297843,2026-06-12 16:57,2026-06-12,16:57
22778,1.781277e+09,2026-06-12 11:14,KLGA,RPA4475,KLGA,1781278244,2026-06-12 11:30,2026-06-12,11:30
23835,1.781564e+09,2026-06-15 18:45,KLGA,N27WA,KLGA,1781565089,2026-06-15 19:11,2026-06-15,19:11
23864,1.781560e+09,2026-06-15 17:42,KLGA,N27WA,KLGA,1781561533,2026-06-15 18:12,2026-06-15,18:12
24937,1.781732e+09,2026-06-17 17:26,KLGA,FXC11,KLGA,1781734439,2026-06-17 18:13,2026-06-17,18:13
25022,1.781721e+09,2026-06-17 14:30,KLGA,N38HF,KLGA,1781725404,2026-06-17 15:43,2026-06-17,15:43
26274,1.781873e+09,2026-06-19 08:51,KLGA,RPA4483,KLGA,1781884163,2026-06-19 11:49,2026-06-19,11:49
27605,1.782137e+09,2026-06-22 10:03,KLGA,FXC55,KLGA,1782137963,2026-06-22 10:19,2026-06-22,10:19
29425,1.782359e+09,2026-06-24 23:36,KLGA,AA9999,KLGA,1782360191,2026-06-25 00:03,2026-06-25,00:03
33563,1.783221e+09,2026-07-04 23:06,KLGA,AA9999,KLGA,1783222319,2026-07-04 23:31,2026-07-04,23:31

In [35]:
df = df[~((df["arr_airport"] == "KLGA") & (df["dep_airport"] == "KLGA"))]
#droping those

In [36]:
df.shape

(50707, 9)

In [37]:
df = df[~((df["arr_airport"] == "KLGA") & (df["dep_airport"] == "KJFK"))]

In [38]:
df[(df["arr_airport"] == "KLGA") & (df["dep_airport"] == "KWER")]
#there isnt any

Empty DataFrame
Columns: [dep_unix, dep_conv, dep_airport, callsign, arr_airport, arrival_unix, arrival_conv, arrival, time]
Index: []

In [39]:
df[(df["arr_airport"] == "KJFK") & (df["dep_airport"] == "KWER")]
#there isnt any

Empty DataFrame
Columns: [dep_unix, dep_conv, dep_airport, callsign, arr_airport, arrival_unix, arrival_conv, arrival, time]
Index: []

In [40]:
df = df[~((df["arr_airport"] == "KJFK") & (df["dep_airport"] == "KLGA"))]
df

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time
0,1.780788e+09,2026-06-06 19:15,NaN,BWA526,KJFK,1780804781,2026-06-06 23:59,2026-06-06,23:59
1,1.780796e+09,2026-06-06 21:32,KFLL,DAL1419,KJFK,1780804705,2026-06-06 23:58,2026-06-06,23:58
2,1.780776e+09,2026-06-06 16:00,NaN,JBU36,KJFK,1780804617,2026-06-06 23:56,2026-06-06,23:56
3,1.780802e+09,2026-06-06 23:08,KBOS,KAL085,KJFK,1780804558,2026-06-06 23:55,2026-06-06,23:55
4,1.780801e+09,2026-06-06 22:51,KBUF,EDV5250,KJFK,1780804403,2026-06-06 23:53,2026-06-06,23:53
...,...,...,...,...,...,...,...,...,...
53219,1.783214e+09,2026-07-04 21:16,KIAH,UAL1444,KEWR,1783225777,2026-07-05 00:29,2026-07-05,00:29
53220,1.783205e+09,2026-07-04 18:43,MMMY,AMX406,KEWR,1783225536,2026-07-05 00:25,2026-07-05,00:25
53221,1.783213e+09,2026-07-04 20:58,KIAH,UAL700,KEWR,1783224771,2026-07-05 00:12,2026-07-05,00:12
53222,1.783213e+09,2026-07-04 20:52,KMCO,JBU1728,KEWR,1783224411,2026-07-05 00:06,2026-07-05,00:06
53223,1.783211e+09,2026-07-04 20:27,KIAH,UAL404T,KEWR,1783224074,2026-07-05 00:01,2026-07-05,00:01

In [41]:
df[(df["arr_airport"] == "KWER") & (df["dep_airport"] == "KJFK")]

Empty DataFrame
Columns: [dep_unix, dep_conv, dep_airport, callsign, arr_airport, arrival_unix, arrival_conv, arrival, time]
Index: []

In [43]:
#lga to lga
#jfk to jfk
#kwer to kwer
#lga to jfk
#lga to kwer
#jfk to kwer
#jfk to lga
#kwer to lga

In [44]:
df.shape

(50670, 9)

In [45]:
df = df[~df["dep_airport"].isin(["KLGA", "KEWR", "KJFK"])]

In [46]:
df.shape

(50457, 9)

In [47]:
df.to_csv("df.csv", index=False)

## Is Brazil in it?

In [48]:
#trying to see if there's any Brazilian airport in the database
br_airports = pd.read_csv("br-airports.csv")

In [49]:
br_airports.head()

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,country_name,iso_country,...,scheduled_service,gps_code,icao_code,iata_code,local_code,home_link,wikipedia_link,keywords,score,last_updated
0,5910,SBGR,large_airport,São Paulo/Guarulhos–Governor André Franco Mont...,-23.431274,-46.469954,2461.0,SA,Brazil,BR,...,1,SBGR,SBGR,GRU,SP0002,http://www.gru.com.br/,https://en.wikipedia.org/wiki/S%C3%A3o_Paulo-G...,Cumbica,1016675,2026-01-17T22:43:52+00:00
1,5906,SBGL,large_airport,Rio Galeão – Tom Jobim International Airport,-22.809999,-43.250557,28.0,SA,Brazil,BR,...,1,SBGL,SBGL,GIG,RJ0001,https://www.riogaleao.com/passageiros,https://en.wikipedia.org/wiki/Rio_de_Janeiro-G...,Galeão - Antônio Carlos Jobim International Ai...,51475,2024-05-09T15:04:08+00:00
2,5974,SBSP,large_airport,Congonhas–Deputado Freitas Nobre Airport,-23.627657,-46.654601,2631.0,SA,Brazil,BR,...,1,SBSP,SBSP,CGH,SP0001,https://www.aenabrasil.com.br/en/airports/cong...,https://en.wikipedia.org/wiki/Congonhas-S%C3%A...,NaN,1000,2026-01-28T19:03:06+00:00
3,5967,SBRJ,large_airport,Santos Dumont Airport,-22.910397,-43.162820,11.0,SA,Brazil,BR,...,1,SBRJ,SBRJ,SDU,RJ0002,https://www4.infraero.gov.br/aeroporto-santos-...,https://en.wikipedia.org/wiki/Santos_Dumont_Ai...,RIO,1000,2026-02-08T15:06:24+00:00
4,5872,SBBR,large_airport,Presidente Juscelino Kubitschek International ...,-15.869167,-47.920834,3497.0,SA,Brazil,BR,...,1,SBBR,SBBR,BSB,DF0001,http://www.infraero.gov.br/usa/aero_prev_home....,https://en.wikipedia.org/wiki/Bras%C3%ADlia_In...,NaN,51275,2020-08-24T11:15:12+00:00

In [50]:
br_airports.columns

Index(['id', 'ident', 'type', 'name', 'latitude_deg', 'longitude_deg',
       'elevation_ft', 'continent', 'country_name', 'iso_country',
       'region_name', 'iso_region', 'local_region', 'municipality',
       'scheduled_service', 'gps_code', 'icao_code', 'iata_code', 'local_code',
       'home_link', 'wikipedia_link', 'keywords', 'score', 'last_updated'],
      dtype='str')

In [51]:
br_airports[['local_region', 'municipality']]

     local_region    municipality
0              SP       São Paulo
1              RJ  Rio De Janeiro
2              SP       São Paulo
3              RJ  Rio de Janeiro
4              DF        Brasília
...           ...             ...
7974           RJ   Volta Redonda
7975           RJ   Volta Redonda
7976           SP      Votorantim
7977           SP      Votorantim
7978           SP      Votorantim

[7979 rows x 2 columns]

In [52]:
br_airports_subset = br_airports[["type", "name", 'local_region', 'municipality', "latitude_deg", "longitude_deg", 'icao_code']]
br_airports_subset

,type,name,local_region,municipality,latitude_deg,longitude_deg,icao_code
0,large_airport,São Paulo/Guarulhos–Governor André Franco Mont...,SP,São Paulo,-23.431274,-46.469954,SBGR
1,large_airport,Rio Galeão – Tom Jobim International Airport,RJ,Rio De Janeiro,-22.809999,-43.250557,SBGL
2,large_airport,Congonhas–Deputado Freitas Nobre Airport,SP,São Paulo,-23.627657,-46.654601,SBSP
3,large_airport,Santos Dumont Airport,RJ,Rio de Janeiro,-22.910397,-43.162820,SBRJ
4,large_airport,Presidente Juscelino Kubitschek International ...,DF,Brasília,-15.869167,-47.920834,SBBR
...,...,...,...,...,...,...,...
7974,closed,Volta Redonda Airport,RJ,Volta Redonda,-22.497800,-44.085000,NaN
7975,heliport,Unimed Volta Redonda Helipad,RJ,Volta Redonda,-22.533988,-44.076918,NaN
7976,heliport,Santa Helena Heliport,SP,Votorantim,-23.598510,-47.441196,NaN
7977,heliport,Bandeiras Centro Empresarial Heliport,SP,Votorantim,-23.536615,-47.449475,SWST
7978,heliport,Alphaville Nova Esplanada 2 Heliport,SP,Votorantim,-23.558971,-47.473779,NaN

In [53]:
br_large_airports = br_airports_subset[br_airports_subset["type"] == "large_airport"]
br_large_airports

,type,name,local_region,municipality,latitude_deg,longitude_deg,icao_code
0,large_airport,São Paulo/Guarulhos–Governor André Franco Mont...,SP,São Paulo,-23.431274,-46.469954,SBGR
1,large_airport,Rio Galeão – Tom Jobim International Airport,RJ,Rio De Janeiro,-22.809999,-43.250557,SBGL
2,large_airport,Congonhas–Deputado Freitas Nobre Airport,SP,São Paulo,-23.627657,-46.654601,SBSP
3,large_airport,Santos Dumont Airport,RJ,Rio de Janeiro,-22.910397,-43.162820,SBRJ
4,large_airport,Presidente Juscelino Kubitschek International ...,DF,Brasília,-15.869167,-47.920834,SBBR
5,large_airport,Deputado Luiz Eduardo Magalhães International ...,BA,Salvador,-12.908611,-38.322498,SBSV
6,large_airport,Porto Alegre-Salgado Filho International Airport,RS,Porto Alegre,-29.993984,-51.167482,SBPA
7,large_airport,Viracopos International Airport,SP,Campinas,-23.007404,-47.134502,SBKP
8,large_airport,Cataratas International Airport,PR,Foz do Iguaçu,-25.594167,-54.489444,SBFI
9,large_airport,Recife/Guararapes - Gilberto Freyre Internatio...,PE,Recife,-8.127470,-34.922961,SBRF
10,large_airport,Pinto Martins International Airport,CE,Fortaleza,-3.775833,-38.532222,SBFZ
11,large_airport,Curitiba-Afonso Pena International Airport,PR,Curitiba,-25.528500,-49.175800,SBCT
12,large_airport,Tancredo Neves International Airport,MG,Belo Horizonte,-19.635710,-43.966928,SBCF
13,large_airport,Eduardo Gomes International Airport,AM,Manaus,-3.038610,-60.049702,SBEG
14,large_airport,Hercílio Luz International Airport,SC,Florianópolis,-27.670279,-48.552502,SBFL
16,large_airport,Val de Cans/Júlio Cezar Ribeiro International ...,PA,Belém,-1.379279,-48.476207,SBBE
18,large_airport,Rio Grande do Norte/São Gonçalo do Amarante–Go...,RN,Natal,-5.769822,-35.366610,NaN
19,large_airport,Santa Genoveva International Airport,GO,Goiânia,-16.632000,-49.220699,SBGO
20,large_airport,Eurico de Aguiar Salles International Airport,ES,Vitória,-20.258000,-40.285000,SBVT
21,large_airport,Várzea Grande–Marechal Rondon International Ai...,MT,Cuiabá,-15.652900,-56.116699,SBCY
23,large_airport,Porto Seguro International Airport,BA,Porto Seguro,-16.438426,-39.080584,SBPS
24,large_airport,Marechal Cunha Machado International Airport,MA,São Luís,-2.586386,-44.235008,SBSL
28,large_airport,Ministro Victor Konder International Airport,SC,Navegantes,-26.879431,-48.650979,SBNF
40,large_airport,Atlas Brasil Cantanhede International Airport,RR,Boa Vista,2.846150,-60.690648,SBBV
41,large_airport,Zumbi dos Palmares International Airport,AL,Maceió,-9.512559,-35.791839,SBMO
52,large_airport,Presidente Castro Pinto International Airport,PB,João Pessoa,-7.148691,-34.950554,SBJP
55,large_airport,Rio Branco-Plácido de Castro International Air...,AC,Rio Branco,-9.869031,-67.893984,SBRB
68,large_airport,Governador Jorge Teixeira de Oliveira Internat...,RO,Porto Velho,-8.708491,-63.902338,SBPV

In [54]:
br_airports_subset[br_airports_subset["type"] == "large_airport"].shape

(28, 7)

In [55]:
br_large_airports["icao_code"]

0     SBGR
1     SBGL
2     SBSP
3     SBRJ
4     SBBR
5     SBSV
6     SBPA
7     SBKP
8     SBFI
9     SBRF
10    SBFZ
11    SBCT
12    SBCF
13    SBEG
14    SBFL
16    SBBE
18     NaN
19    SBGO
20    SBVT
21    SBCY
23    SBPS
24    SBSL
28    SBNF
40    SBBV
41    SBMO
52    SBJP
55    SBRB
68    SBPV
Name: icao_code, dtype: str

In [56]:
icao_brasil = br_large_airports["icao_code"].tolist()

In [57]:
icao_brasil

['SBGR',
 'SBGL',
 'SBSP',
 'SBRJ',
 'SBBR',
 'SBSV',
 'SBPA',
 'SBKP',
 'SBFI',
 'SBRF',
 'SBFZ',
 'SBCT',
 'SBCF',
 'SBEG',
 'SBFL',
 'SBBE',
 nan,
 'SBGO',
 'SBVT',
 'SBCY',
 'SBPS',
 'SBSL',
 'SBNF',
 'SBBV',
 'SBMO',
 'SBJP',
 'SBRB',
 'SBPV']

In [59]:
type(icao_brasil)

list

In [62]:
flights_brasil = df[df["dep_airport"].isin(icao_brasil)]

print(f"{len(flights_brasil)} flights departured from Brazil to NY")
print(flights_brasil)

4839 flights departured from Brazil to NY
           dep_unix          dep_conv dep_airport  callsign arr_airport  \
0      1.780788e+09  2026-06-06 19:15         NaN  BWA526          KJFK
2      1.780776e+09  2026-06-06 16:00         NaN  JBU36           KJFK
8      1.780795e+09  2026-06-06 21:16         NaN  AVA144          KJFK
19     1.780790e+09  2026-06-06 19:48         NaN  BWA554          KJFK
28     1.780800e+09  2026-06-06 22:35         NaN  DAL1863         KJFK
...             ...               ...         ...       ...         ...
53173  1.783230e+09  2026-07-05 01:44         NaN  UAL2450         KEWR
53177  1.783211e+09  2026-07-04 20:20        SBGR  UAL148          KEWR
53180  1.783226e+09  2026-07-05 00:37         NaN  VOI1902         KEWR
53181  1.783232e+09  2026-07-05 02:11         NaN  UAL1703         KEWR
53190  1.783234e+09  2026-07-05 02:39         NaN  UAL1162         KEWR

       arrival_unix      arrival_conv     arrival   time
0        1780804781  2026-06-06 23:59  2026-06-06  23:59
2        1780804617  2026-06-06 23:56  2026-06-06  23:56
8        1780803989  2026-06-06 23:46  2026-06-06  23:46
19       1780802956  2026-06-06 23:29  2026-06-06  23:29
28       1780801758  2026-06-06 23:09  2026-06-06  23:09
...             ...               ...         ...    ...
53173    1783243076  2026-07-05 05:17  2026-07-05  05:17
53177    1783241819  2026-07-05 04:56  2026-07-05  04:56
53180    1783240489  2026-07-05 04:34  2026-07-05  04:34
53181    1783240169  2026-07-05 04:29  2026-07-05  04:29
53190    1783236836  2026-07-05 03:33  2026-07-05  03:33

[4839 rows x 9 columns]

In [63]:
df["from_brazil"] = df["dep_airport"].isin(icao_brasil)
#creating nem column to show if the flight came from brazil

In [64]:
df[df["from_brazil"] == True].groupby("arrival").size().sort_values(ascending=False)

arrival
2026-06-27    197
2026-06-06    182
2026-06-28    179
2026-06-21    177
2026-06-20    172
2026-06-19    172
2026-06-11    171
2026-06-25    171
2026-06-26    168
2026-07-01    168
2026-07-02    167
2026-06-22    166
2026-06-13    165
2026-06-30    162
2026-07-05    161
2026-06-18    161
2026-06-23    161
2026-06-29    160
2026-06-12    158
2026-06-14    158
2026-06-15    157
2026-06-07    157
2026-06-24    157
2026-07-03    152
2026-06-09    145
2026-06-17    143
2026-06-16    139
2026-07-04    139
2026-06-08    137
2026-06-10    137
dtype: int64

## analysis

In [65]:
arrivals_by_airport = df.groupby("arr_airport")["arrival"].count()
arrivals_by_airport 
#flights by airport

arr_airport
KEWR    16944
KJFK    18994
KLGA    14519
Name: arrival, dtype: int64

In [66]:
arrivals_by_airport.to_csv("arrivals_by_airport.csv")

In [67]:
arrivals_per_day = df.groupby("arrival")["arr_airport"].count()
arrivals_per_day

arrival
2026-06-06    1317
2026-06-07    1714
2026-06-08    1789
2026-06-09    1796
2026-06-10    1572
2026-06-11    1670
2026-06-12    1532
2026-06-13    1598
2026-06-14    1474
2026-06-15    1760
2026-06-16    1781
2026-06-17    1768
2026-06-18    1794
2026-06-19    1825
2026-06-20    1550
2026-06-21    1770
2026-06-22    1482
2026-06-23    1806
2026-06-24    1838
2026-06-25    1862
2026-06-26    1854
2026-06-27    1547
2026-06-28    1765
2026-06-29    1782
2026-06-30    1760
2026-07-01    1807
2026-07-02    1846
2026-07-03    1653
2026-07-04    1247
2026-07-05    1498
Name: arr_airport, dtype: int64

In [68]:
arrivals_per_day.describe()

count      30.00000
mean     1681.90000
std       163.42632
min      1247.00000
25%      1555.50000
50%      1762.50000
75%      1795.50000
max      1862.00000
Name: arr_airport, dtype: float64

In [69]:
arrivals_per_day.to_csv("arrivals_per_day.csv")

In [117]:
((1789 - 1681)/1681)*100
#less busy from top 10 busiest days compared to mean

6.424747174301011

In [116]:
((1862- 1681)/1681)*100
#busiest day compared to mean

10.767400356930398

In [72]:
#top 10 days that NY received more flights
top_10_days = df.groupby("arrival")["arr_airport"].count().sort_values(ascending=False).head(10)
top_10_days
#9 out of the 10 busiest days at New York airports occurred 4 days before a game
#6 out of the 10 busiest days at New York airports occurred 3 days before a game
#4 out of the 10 busiest days at New York airports occurred 2 days before a game

arrival
2026-06-25    1862
2026-06-26    1854
2026-07-02    1846
2026-06-24    1838
2026-06-19    1825
2026-07-01    1807
2026-06-23    1806
2026-06-09    1796
2026-06-18    1794
2026-06-08    1789
Name: arr_airport, dtype: int64

In [73]:
top_10_days.to_csv("top_10_days.csv")

In [114]:
dep_airports = df["dep_airport"].value_counts().sort_values(ascending=False).head(50)
dep_airports
#top 50 airports
#US 44
#Canada 3 (Toronto Pearson, Toronto City e Montreal)
#UK 1 (Heathrow)
#France 1 (Paris Charles de Gaulle)
#Italy 1 (Roma Fiumicino)

dep_airport
KORD    1651
KATL    1428
KBOS    1424
KLAX    1186
KMCO    1110
KMIA    1061
CYYZ    1060
KDFW     979
KSFO     930
KCLT     906
EGLL     896
KFLL     891
KDEN     830
KRDU     822
KDCA     779
KBNA     722
KIAH     722
KDTW     653
KIND     635
KPIT     629
KPBI     573
KTPA     566
KCLE     565
KCVG     557
KCMH     516
KMSP     498
KLAS     494
KBUF     488
TJSJ     481
KIAD     479
KSEA     477
CYUL     476
LFPG     459
KPHX     437
KCHS     398
KRIC     389
KJAX     388
KORF     378
KSTL     363
KSDF     352
KSAN     339
KAUS     337
PANC     315
LIRF     314
KROC     303
KMSY     268
CYTZ     268
KSAV     267
KBGR     254
KSLC     252
Name: count, dtype: int64

In [76]:
dep_airports.to_csv("dep_airports.csv")

## analysis by match

In [77]:
#filter arrivals 4 hours before the match
#first match was 2026-06-13	18:00:00 Brazil vs Morocco

In [78]:
df["arrival_conv"].dtype

In [79]:
df["arrival_unix"].dtype #wil compare using unix so I don't have to convert it

dtype('int64')

In [80]:
df[df["arrival_conv"] == "2026-06-13 14:00"]

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time,from_brazil
4807,1.781368e+09,2026-06-13 12:25,KIND,EDV4976,KJFK,1781373634,2026-06-13 14:00,2026-06-13,14:00,False

In [81]:
flights_1game = df[df["arrival_unix"] < 1781373634].sort_values("arrival_conv")
flights_1game

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time,from_brazil
34748,1.780708e+09,2026-06-05 21:06,KIAH,UAL8244,KEWR,1780718466,2026-06-06 00:01,2026-06-06,00:01,False
34747,1.780703e+09,2026-06-05 19:39,KSEA,ASA293,KEWR,1780718636,2026-06-06 00:03,2026-06-06,00:03,False
34746,1.780711e+09,2026-06-05 21:57,KMSP,DAL2846,KEWR,1780718810,2026-06-06 00:06,2026-06-06,00:06,False
34745,1.780703e+09,2026-06-05 19:35,KLAX,UAL1700,KEWR,1780718984,2026-06-06 00:09,2026-06-06,00:09,False
554,1.780717e+09,2026-06-05 23:31,NaN,JBU210,KJFK,1780719476,2026-06-06 00:17,2026-06-06,00:17,True
...,...,...,...,...,...,...,...,...,...,...
38869,1.781346e+09,2026-06-13 06:14,LEBL,UAL121,KEWR,1781373368,2026-06-13 13:56,2026-06-13,13:56,False
4809,1.781348e+09,2026-06-13 07:00,EGPH,AAL83,KJFK,1781373517,2026-06-13 13:58,2026-06-13,13:58,False
23112,1.781369e+09,2026-06-13 12:48,CYYZ,RPA4623,KLGA,1781373531,2026-06-13 13:58,2026-06-13,13:58,False
38866,1.781367e+09,2026-06-13 12:12,KATL,DAL2312,KEWR,1781373505,2026-06-13 13:58,2026-06-13,13:58,False
4808,1.781368e+09,2026-06-13 12:21,KORD,RPA4356,KJFK,1781373594,2026-06-13 13:59,2026-06-13,13:59,False

In [82]:
game1_per_day = flights_1game.value_counts("arrival").sort_index()
game1_per_day

arrival
2026-06-06    1317
2026-06-07    1714
2026-06-08    1789
2026-06-09    1796
2026-06-10    1572
2026-06-11    1670
2026-06-12    1532
2026-06-13     745
Name: count, dtype: int64

In [83]:
flights_1game.value_counts("dep_airport").sort_values(ascending=False).head(20)

dep_airport
KORD    376
KATL    362
KBOS    360
KLAX    278
KMCO    270
KMIA    259
CYYZ    249
KSFO    236
KDFW    233
KFLL    221
KCLT    218
EGLL    218
KRDU    208
KDEN    203
KDCA    182
KIAH    177
KBNA    176
KDTW    164
KPIT    153
KIND    150
Name: count, dtype: int64

In [84]:
############# game 2 2026-06-16	15:00:00	France	Senegal
df[df["arrival_conv"] == "2026-06-16 11:01"]

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time,from_brazil
6852,1.781616e+09,2026-06-16 09:22,KATL,FFT4732,KJFK,1781622106,2026-06-16 11:01,2026-06-16,11:01,False
6853,1.781618e+09,2026-06-16 09:49,KCLT,AAL374,KJFK,1781622093,2026-06-16 11:01,2026-06-16,11:01,False
40895,1.781620e+09,2026-06-16 10:28,KDCA,GJS4184,KEWR,1781622119,2026-06-16 11:01,2026-06-16,11:01,False

In [85]:
flights_2game = df[df["arrival_unix"] < 1781622093].sort_values("arrival_conv")
flights_2game

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time,from_brazil
34748,1.780708e+09,2026-06-05 21:06,KIAH,UAL8244,KEWR,1780718466,2026-06-06 00:01,2026-06-06,00:01,False
34747,1.780703e+09,2026-06-05 19:39,KSEA,ASA293,KEWR,1780718636,2026-06-06 00:03,2026-06-06,00:03,False
34746,1.780711e+09,2026-06-05 21:57,KMSP,DAL2846,KEWR,1780718810,2026-06-06 00:06,2026-06-06,00:06,False
34745,1.780703e+09,2026-06-05 19:35,KLAX,UAL1700,KEWR,1780718984,2026-06-06 00:09,2026-06-06,00:09,False
554,1.780717e+09,2026-06-05 23:31,NaN,JBU210,KJFK,1780719476,2026-06-06 00:17,2026-06-06,00:17,True
...,...,...,...,...,...,...,...,...,...,...
6856,1.781591e+09,2026-06-16 02:23,LIRF,AIC101,KJFK,1781621819,2026-06-16 10:56,2026-06-16,10:56,False
24639,1.781616e+09,2026-06-16 09:22,KORD,AAL2079,KLGA,1781621869,2026-06-16 10:57,2026-06-16,10:57,False
6855,1.781596e+09,2026-06-16 03:54,EGLL,VIR3N,KJFK,1781621938,2026-06-16 10:58,2026-06-16,10:58,False
6854,1.781618e+09,2026-06-16 09:53,MA44,KAP811,KJFK,1781621968,2026-06-16 10:59,2026-06-16,10:59,False
24638,1.781620e+09,2026-06-16 10:19,KBOS,RPA5744,KLGA,1781621976,2026-06-16 10:59,2026-06-16,10:59,False

In [86]:
game2_per_day = flights_2game.value_counts("arrival").sort_index()
game2_per_day

arrival
2026-06-06    1317
2026-06-07    1714
2026-06-08    1789
2026-06-09    1796
2026-06-10    1572
2026-06-11    1670
2026-06-12    1532
2026-06-13    1598
2026-06-14    1474
2026-06-15    1760
2026-06-16     494
Name: count, dtype: int64

In [87]:
flights_2game.value_counts("dep_airport").sort_values(ascending=False).head(20)

dep_airport
KORD    530
KBOS    488
KATL    482
KLAX    395
KMCO    371
KMIA    356
CYYZ    339
KSFO    325
KDFW    314
KCLT    303
EGLL    303
KFLL    295
KDEN    280
KRDU    279
KDCA    256
KIAH    241
KBNA    241
KDTW    214
KPIT    212
KIND    207
Name: count, dtype: int64

In [88]:
##### game 3
#2026-06-22	20:00:00	Norway	Senegal
df[df["arrival_conv"] == "2026-06-22 16:01"]

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time,from_brazil
10628,1.782133e+09,2026-06-22 08:55,EGLL,BAW04A,KJFK,1782158487,2026-06-22 16:01,2026-06-22,16:01,False

In [89]:
flights_3game = df[df["arrival_unix"] < 1782158487].sort_values("arrival_conv")
flights_3game

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time,from_brazil
34748,1.780708e+09,2026-06-05 21:06,KIAH,UAL8244,KEWR,1780718466,2026-06-06 00:01,2026-06-06,00:01,False
34747,1.780703e+09,2026-06-05 19:39,KSEA,ASA293,KEWR,1780718636,2026-06-06 00:03,2026-06-06,00:03,False
34746,1.780711e+09,2026-06-05 21:57,KMSP,DAL2846,KEWR,1780718810,2026-06-06 00:06,2026-06-06,00:06,False
34745,1.780703e+09,2026-06-05 19:35,KLAX,UAL1700,KEWR,1780718984,2026-06-06 00:09,2026-06-06,00:09,False
554,1.780717e+09,2026-06-05 23:31,NaN,JBU210,KJFK,1780719476,2026-06-06 00:17,2026-06-06,00:17,True
...,...,...,...,...,...,...,...,...,...,...
27465,1.782155e+09,2026-06-22 15:02,KHYA,RPA4565,KLGA,1782158142,2026-06-22 15:55,2026-06-22,15:55,False
10631,1.782128e+09,2026-06-22 07:33,LFMN,DAL8771,KJFK,1782158178,2026-06-22 15:56,2026-06-22,15:56,False
44558,1.782146e+09,2026-06-22 12:35,KDEN,UAL2381,KEWR,1782158189,2026-06-22 15:56,2026-06-22,15:56,False
10630,1.782146e+09,2026-06-22 12:37,MMUN,AAL1185,KJFK,1782158320,2026-06-22 15:58,2026-06-22,15:58,False
10629,1.782147e+09,2026-06-22 12:53,KDFW,AAL1135,KJFK,1782158398,2026-06-22 15:59,2026-06-22,15:59,False

In [90]:
flights_3game.value_counts("arrival").sort_index()

arrival
2026-06-06    1317
2026-06-07    1714
2026-06-08    1789
2026-06-09    1796
2026-06-10    1572
2026-06-11    1670
2026-06-12    1532
2026-06-13    1598
2026-06-14    1474
2026-06-15    1760
2026-06-16    1781
2026-06-17    1768
2026-06-18    1794
2026-06-19    1825
2026-06-20    1550
2026-06-21    1770
2026-06-22     944
Name: count, dtype: int64

In [91]:
flights_3game.value_counts("dep_airport").sort_values(ascending=False).head(20)

dep_airport
KORD    896
KBOS    793
KATL    792
KLAX    650
KMCO    609
KMIA    585
CYYZ    580
KSFO    520
KDFW    518
KCLT    500
EGLL    497
KFLL    486
KDEN    465
KRDU    462
KDCA    436
KBNA    402
KIAH    390
KDTW    353
KIND    346
KPIT    343
Name: count, dtype: int64

In [92]:
### game 4 2026-06-25	16:00:00	Ecuador	Germany
df[df["arrival_conv"] == "2026-06-25 12:00"]

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time,from_brazil
29253,1.782401e+09,2026-06-25 11:16,KBOS,RPA4373,KLGA,1782403216,2026-06-25 12:00,2026-06-25,12:00,False
46711,1.782397e+09,2026-06-25 10:22,KATL,DAL2401,KEWR,1782403256,2026-06-25 12:00,2026-06-25,12:00,False

In [93]:
flights_4game = df[df["arrival_unix"] < 1782403216].sort_values("arrival_conv")
flights_4game

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time,from_brazil
34748,1.780708e+09,2026-06-05 21:06,KIAH,UAL8244,KEWR,1780718466,2026-06-06 00:01,2026-06-06,00:01,False
34747,1.780703e+09,2026-06-05 19:39,KSEA,ASA293,KEWR,1780718636,2026-06-06 00:03,2026-06-06,00:03,False
34746,1.780711e+09,2026-06-05 21:57,KMSP,DAL2846,KEWR,1780718810,2026-06-06 00:06,2026-06-06,00:06,False
34745,1.780703e+09,2026-06-05 19:35,KLAX,UAL1700,KEWR,1780718984,2026-06-06 00:09,2026-06-06,00:09,False
554,1.780717e+09,2026-06-05 23:31,NaN,JBU210,KJFK,1780719476,2026-06-06 00:17,2026-06-06,00:17,True
...,...,...,...,...,...,...,...,...,...,...
29255,1.782400e+09,2026-06-25 11:13,KBOS,RPA5755,KLGA,1782403097,2026-06-25 11:58,2026-06-25,11:58,False
46713,1.782400e+09,2026-06-25 11:04,KRIC,GJS4493,KEWR,1782403133,2026-06-25 11:58,2026-06-25,11:58,False
12837,1.782396e+09,2026-06-25 09:58,KBNA,RPA4712,KJFK,1782403198,2026-06-25 11:59,2026-06-25,11:59,False
29254,1.782400e+09,2026-06-25 11:01,KPIT,RPA5796,KLGA,1782403163,2026-06-25 11:59,2026-06-25,11:59,False
46712,1.782394e+09,2026-06-25 09:34,KMIA,UAL408,KEWR,1782403195,2026-06-25 11:59,2026-06-25,11:59,False

In [94]:
flights_4game.value_counts("arrival").sort_index()

arrival
2026-06-06    1317
2026-06-07    1714
2026-06-08    1789
2026-06-09    1796
2026-06-10    1572
2026-06-11    1670
2026-06-12    1532
2026-06-13    1598
2026-06-14    1474
2026-06-15    1760
2026-06-16    1781
2026-06-17    1768
2026-06-18    1794
2026-06-19    1825
2026-06-20    1550
2026-06-21    1770
2026-06-22    1482
2026-06-23    1806
2026-06-24    1838
2026-06-25     586
Name: count, dtype: int64

In [95]:
flights_4game.value_counts("dep_airport").sort_values(ascending=False).head(20)

dep_airport
KORD    1058
KBOS     944
KATL     930
KLAX     766
KMCO     713
CYYZ     685
KMIA     684
KDFW     622
KSFO     612
KCLT     587
EGLL     576
KFLL     570
KDEN     544
KRDU     540
KDCA     514
KBNA     470
KIAH     461
KDTW     418
KIND     411
KPIT     409
Name: count, dtype: int64

In [96]:
### game 5 	2026-06-27	17:00:00	Panama	England
df[df["arrival_conv"] == "2026-06-27 13:01"]

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time,from_brazil
14160,1.782575e+09,2026-06-27 11:39,KCLT,EDV5052,KJFK,1782579719,2026-06-27 13:01,2026-06-27,13:01,False
47993,1.782557e+09,2026-06-27 06:46,PANC,FDX6030,KEWR,1782579719,2026-06-27 13:01,2026-06-27,13:01,False

In [97]:
flights_5game = df[df["arrival_unix"] < 1782579719].sort_values("arrival_conv")
flights_5game

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time,from_brazil
34748,1.780708e+09,2026-06-05 21:06,KIAH,UAL8244,KEWR,1780718466,2026-06-06 00:01,2026-06-06,00:01,False
34747,1.780703e+09,2026-06-05 19:39,KSEA,ASA293,KEWR,1780718636,2026-06-06 00:03,2026-06-06,00:03,False
34746,1.780711e+09,2026-06-05 21:57,KMSP,DAL2846,KEWR,1780718810,2026-06-06 00:06,2026-06-06,00:06,False
34745,1.780703e+09,2026-06-05 19:35,KLAX,UAL1700,KEWR,1780718984,2026-06-06 00:09,2026-06-06,00:09,False
554,1.780717e+09,2026-06-05 23:31,NaN,JBU210,KJFK,1780719476,2026-06-06 00:17,2026-06-06,00:17,True
...,...,...,...,...,...,...,...,...,...,...
14163,1.782560e+09,2026-06-27 07:39,BIKF,DAL247,KJFK,1782579395,2026-06-27 12:56,2026-06-27,12:56,False
30232,1.782575e+09,2026-06-27 11:41,NaN,DAL2194,KLGA,1782579455,2026-06-27 12:57,2026-06-27,12:57,True
14162,1.782571e+09,2026-06-27 10:31,KMIA,AAL1052,KJFK,1782579486,2026-06-27 12:58,2026-06-27,12:58,False
14161,1.782556e+09,2026-06-27 06:29,EIDW,EIN105,KJFK,1782579586,2026-06-27 12:59,2026-06-27,12:59,False
30231,1.782575e+09,2026-06-27 11:50,KBGR,RPA4343,KLGA,1782579594,2026-06-27 12:59,2026-06-27,12:59,False

In [98]:
flights_5game.value_counts("arrival").sort_index()

arrival
2026-06-06    1317
2026-06-07    1714
2026-06-08    1789
2026-06-09    1796
2026-06-10    1572
2026-06-11    1670
2026-06-12    1532
2026-06-13    1598
2026-06-14    1474
2026-06-15    1760
2026-06-16    1781
2026-06-17    1768
2026-06-18    1794
2026-06-19    1825
2026-06-20    1550
2026-06-21    1770
2026-06-22    1482
2026-06-23    1806
2026-06-24    1838
2026-06-25    1862
2026-06-26    1854
2026-06-27     577
Name: count, dtype: int64

In [99]:
flights_5game.value_counts("dep_airport").sort_values(ascending=False).head(20)

dep_airport
KORD    1184
KBOS    1044
KATL    1036
KLAX     853
KMCO     795
CYYZ     770
KMIA     760
KDFW     698
KSFO     678
KCLT     654
EGLL     639
KFLL     634
KDEN     604
KRDU     604
KDCA     575
KBNA     522
KIAH     512
KDTW     466
KIND     459
KPIT     451
Name: count, dtype: int64

In [101]:
### game 6 	2026-06-30	17:00:00	France	Sweden
df[df["arrival_conv"] == "2026-06-30 13:00"]

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time,from_brazil
16179,1.782835e+09,2026-06-30 11:51,KCLE,EDV5018,KJFK,1782838829,2026-06-30 13:00,2026-06-30,13:00,False
31770,1.782830e+09,2026-06-30 10:31,KMIA,AAL3256,KLGA,1782838819,2026-06-30 13:00,2026-06-30,13:00,False

In [104]:
flights_6game = df[df["arrival_unix"] < 1782838829].sort_values("arrival_conv")
flights_6game

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time,from_brazil
34748,1.780708e+09,2026-06-05 21:06,KIAH,UAL8244,KEWR,1780718466,2026-06-06 00:01,2026-06-06,00:01,False
34747,1.780703e+09,2026-06-05 19:39,KSEA,ASA293,KEWR,1780718636,2026-06-06 00:03,2026-06-06,00:03,False
34746,1.780711e+09,2026-06-05 21:57,KMSP,DAL2846,KEWR,1780718810,2026-06-06 00:06,2026-06-06,00:06,False
34745,1.780703e+09,2026-06-05 19:35,KLAX,UAL1700,KEWR,1780718984,2026-06-06 00:09,2026-06-06,00:09,False
554,1.780717e+09,2026-06-05 23:31,NaN,JBU210,KJFK,1780719476,2026-06-06 00:17,2026-06-06,00:17,True
...,...,...,...,...,...,...,...,...,...,...
31771,1.782835e+09,2026-06-30 11:55,CYYZ,ACA708,KLGA,1782838640,2026-06-30 12:57,2026-06-30,12:57,False
49929,1.782834e+09,2026-06-30 11:41,KBOS,MTN8310,KEWR,1782838648,2026-06-30 12:57,2026-06-30,12:57,False
16180,1.782830e+09,2026-06-30 10:35,KMIA,AAL1052,KJFK,1782838706,2026-06-30 12:58,2026-06-30,12:58,False
49928,1.782829e+09,2026-06-30 10:15,NaN,GXA6111,KEWR,1782838751,2026-06-30 12:59,2026-06-30,12:59,True
31770,1.782830e+09,2026-06-30 10:31,KMIA,AAL3256,KLGA,1782838819,2026-06-30 13:00,2026-06-30,13:00,False

In [105]:
flights_6game.value_counts("arrival").sort_index()

arrival
2026-06-06    1317
2026-06-07    1714
2026-06-08    1789
2026-06-09    1796
2026-06-10    1572
2026-06-11    1670
2026-06-12    1532
2026-06-13    1598
2026-06-14    1474
2026-06-15    1760
2026-06-16    1781
2026-06-17    1768
2026-06-18    1794
2026-06-19    1825
2026-06-20    1550
2026-06-21    1770
2026-06-22    1482
2026-06-23    1806
2026-06-24    1838
2026-06-25    1862
2026-06-26    1854
2026-06-27    1547
2026-06-28    1765
2026-06-29    1782
2026-06-30     660
Name: count, dtype: int64

In [107]:
flights_6game.value_counts("dep_airport").sort_values(ascending=False).head(20)

dep_airport
KORD    1356
KATL    1181
KBOS    1179
KLAX     976
KMCO     911
CYYZ     884
KMIA     870
KDFW     798
KSFO     773
KCLT     749
KFLL     728
EGLL     727
KDEN     686
KRDU     685
KDCA     660
KBNA     597
KIAH     590
KDTW     532
KIND     523
KPIT     515
Name: count, dtype: int64

In [108]:
##game 7 2026-07-05	16:00:00	Brazil	Noruega
df[df["arrival_conv"] == "2026-07-05 12:00"]

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time,from_brazil
19425,1.783259e+09,2026-07-05 09:49,KMCO,JBU384,KJFK,1783267227,2026-07-05 12:00,2026-07-05,12:00,False
34092,1.783266e+09,2026-07-05 11:35,K3C8,N726SH,KLGA,1783267239,2026-07-05 12:00,2026-07-05,12:00,False
34093,1.783265e+09,2026-07-05 11:15,KIAD,KOW106,KLGA,1783267218,2026-07-05 12:00,2026-07-05,12:00,False

In [112]:
flights_7game = df[df["arrival_unix"] < 1783267227].sort_values("arrival_conv")
flights_7game

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time,from_brazil
34748,1.780708e+09,2026-06-05 21:06,KIAH,UAL8244,KEWR,1780718466,2026-06-06 00:01,2026-06-06,00:01,False
34747,1.780703e+09,2026-06-05 19:39,KSEA,ASA293,KEWR,1780718636,2026-06-06 00:03,2026-06-06,00:03,False
34746,1.780711e+09,2026-06-05 21:57,KMSP,DAL2846,KEWR,1780718810,2026-06-06 00:06,2026-06-06,00:06,False
34745,1.780703e+09,2026-06-05 19:35,KLAX,UAL1700,KEWR,1780718984,2026-06-06 00:09,2026-06-06,00:09,False
554,1.780717e+09,2026-06-05 23:31,NaN,JBU210,KJFK,1780719476,2026-06-06 00:17,2026-06-06,00:17,True
...,...,...,...,...,...,...,...,...,...,...
19427,1.783240e+09,2026-07-05 04:33,LEMD,AAL95,KJFK,1783267013,2026-07-05 11:56,2026-07-05,11:56,False
19428,1.783259e+09,2026-07-05 09:50,KBNA,RPA4712,KJFK,1783266964,2026-07-05 11:56,2026-07-05,11:56,False
34094,1.783264e+09,2026-07-05 11:03,KORF,RPA4473,KLGA,1783267071,2026-07-05 11:57,2026-07-05,11:57,False
19426,1.783260e+09,2026-07-05 10:04,KATL,DAL1034,KJFK,1783267138,2026-07-05 11:58,2026-07-05,11:58,False
34093,1.783265e+09,2026-07-05 11:15,KIAD,KOW106,KLGA,1783267218,2026-07-05 12:00,2026-07-05,12:00,False

In [113]:
flights_7game.value_counts("arrival").sort_index()

arrival
2026-06-06    1317
2026-06-07    1714
2026-06-08    1789
2026-06-09    1796
2026-06-10    1572
2026-06-11    1670
2026-06-12    1532
2026-06-13    1598
2026-06-14    1474
2026-06-15    1760
2026-06-16    1781
2026-06-17    1768
2026-06-18    1794
2026-06-19    1825
2026-06-20    1550
2026-06-21    1770
2026-06-22    1482
2026-06-23    1806
2026-06-24    1838
2026-06-25    1862
2026-06-26    1854
2026-06-27    1547
2026-06-28    1765
2026-06-29    1782
2026-06-30    1760
2026-07-01    1807
2026-07-02    1846
2026-07-03    1653
2026-07-04    1247
2026-07-05     558
Name: count, dtype: int64

## geocoding airports

In [3]:
load_dotenv()

True

In [4]:
api_key_geocoder = os.environ["api_key_geocoder"]

In [5]:
api_key_geocoder[:9]+"..."

'AIzaSyDI7...'

In [6]:
top_50_airports = pd.read_csv('top50_airports.csv')

In [7]:
top_50_airports.head(5)

,ICAO,Airport,City/Country
0,KORD,O'Hare International Airport,"Chicago, Illinois, EUA"
1,KATL,Hartsfield–Jackson Atlanta International Airport,"Atlanta, Geórgia, EUA"
2,KBOS,Logan International Airport,"Boston, Massachusetts, EUA"
3,KLAX,Los Angeles International Airport,"Los Angeles, Califórnia, EUA"
4,KMCO,Orlando International Airport,"Orlando, Flórida, EUA"

In [8]:
#getting the latitude and longitude
for index, row in top_50_airports.iterrows():
    full_address = f"{row['ICAO']}, {row['Airport']}, {row['City/Country']}"
    print(full_address)
    
    geo = geocoder.google(full_address, key=api_key_geocoder)
    print("Status:", geo.status)
    print("OK:", geo.ok)
    print("LatLng:", geo.latlng)
    
    if geo.ok:
        top_50_airports.loc[index, "lat"] = geo.latlng[0]
        top_50_airports.loc[index, "long"] = geo.latlng[1]
    else:
        print(f"Failed for {full_address}: {geo.status}")

top_50_airports

KORD, O'Hare International Airport, Chicago, Illinois, EUA
Status: OK
OK: True
LatLng: [41.97684, -87.90474999999999]
KATL, Hartsfield–Jackson Atlanta International Airport, Atlanta, Geórgia, EUA
Status: OK
OK: True
LatLng: [33.6324187, -84.4333116]
KBOS, Logan International Airport, Boston, Massachusetts, EUA
Status: OK
OK: True
LatLng: [42.3658907, -71.017547]
KLAX, Los Angeles International Airport, Los Angeles, Califórnia, EUA
Status: OK
OK: True
LatLng: [33.942153, -118.4036052]
KMCO, Orlando International Airport, Orlando, Flórida, EUA
Status: OK
OK: True
LatLng: [28.432216, -81.30779969999999]
KMIA, Miami International Airport, Miami, Flórida, EUA
Status: OK
OK: True
LatLng: [25.7923496, -80.28230590000001]
CYYZ, Toronto Pearson International Airport, Toronto, Ontário, Canadá
Status: OK
OK: True
LatLng: [43.6798345, -79.62838339999999]
KDFW, Dallas Fort Worth International Airport, Dallas–Fort Worth, Texas, EUA
Status: OK
OK: True
LatLng: [32.8921983, -97.03912319999999]
KSFO, San Francisco International Airport, San Francisco, Califórnia, EUA
Status: OK
OK: True
LatLng: [37.61911449999999, -122.3816274]
KCLT, Charlotte Douglas International Airport, Charlotte, Carolina do Norte, EUA
Status: OK
OK: True
LatLng: [35.2162994, -80.95394280000001]
EGLL, Heathrow Airport, Londres, Reino Unido
Status: OK
OK: True
LatLng: [51.4679903, -0.4550471]
KFLL, Fort Lauderdale–Hollywood International Airport, Fort Lauderdale, Flórida, EUA
Status: OK
OK: True
LatLng: [26.0731729, -80.1512317]
KDEN, Denver International Airport, Denver, Colorado, EUA
Status: OK
OK: True
LatLng: [39.8563486, -104.6764061]
KRDU, Raleigh–Durham International Airport, Raleigh–Durham, Carolina do Norte, EUA
Status: OK
OK: True
LatLng: [35.8797678, -78.7855512]
KDCA, Ronald Reagan Washington National Airport, Arlington (Washington, D.C.), EUA
Status: OK
OK: True
LatLng: [38.8530281, -77.0427924]
KBNA, Nashville International Airport, Nashville, Tennessee, EUA
Status: OK
OK: True
LatLng: [36.1308194, -86.66611449999999]
KIAH, George Bush Intercontinental Airport, Houston, Texas, EUA
Status: OK
OK: True
LatLng: [29.9931058, -95.34162549999999]
KDTW, Detroit Metropolitan Wayne County Airport, Detroit, Michigan, EUA
Status: OK
OK: True
LatLng: [42.2132203, -83.3524824]
KIND, Indianapolis International Airport, Indianapolis, Indiana, EUA
Status: OK
OK: True
LatLng: [39.7149625, -86.2977052]
KPIT, Pittsburgh International Airport, Pittsburgh, Pensilvânia, EUA
Status: OK
OK: True
LatLng: [40.4928544, -80.2372942]
KPBI, Palm Beach International Airport, West Palm Beach, Flórida, EUA
Status: OK
OK: True
LatLng: [26.6857475, -80.0928165]
KTPA, Tampa International Airport, Tampa, Flórida, EUA
Status: OK
OK: True
LatLng: [27.9768646, -82.5302804]
KCLE, Cleveland Hopkins International Airport, Cleveland, Ohio, EUA
Status: OK
OK: True
LatLng: [41.4057985, -81.8538669]
KCVG, Cincinnati/Northern Kentucky International Airport, Hebron (Cincinnati), Kentucky, EUA
Status: OK
OK: True
LatLng: [39.051351, -84.6671453]
KCMH, John Glenn Columbus International Airport, Columbus, Ohio, EUA
Status: OK
OK: True
LatLng: [39.998728, -82.884463]
KMSP, Minneapolis–Saint Paul International Airport, Minneapolis–Saint Paul, Minnesota, EUA
Status: OK
OK: True
LatLng: [44.8850593, -93.2144354]
KLAS, Harry Reid International Airport, Las Vegas, Nevada, EUA
Status: OK
OK: True
LatLng: [36.08309070000001, -115.1482238]
KBUF, Buffalo Niagara International Airport, Buffalo, Nova York, EUA
Status: OK
OK: True
LatLng: [42.9394052, -78.73350119999999]
TJSJ, Luis Muñoz Marín International Airport, San Juan, Porto Rico
Status: OK
OK: True
LatLng: [18.4395043, -65.9992275]
KIAD, Washington Dulles International Airport, Washington, D.C. (Virgínia), EUA
Status: OK
OK: True
LatLng: [38.9522483, -77.45788859999999]
KSEA, Seattle–Tacoma International Airport, Seattle, Washington, EUA
Status: OK
OK: True
LatLng: [47.4483652, -122.3085927]
CYUL, Montréal–Trudeau International Airport, Montreal, Québec, Canadá
Status: OK
OK: True
LatLng: [45.465787, -73.7454044]
LFPG, Charles de Gaulle Airport, Paris, França
Status: OK
OK: True
LatLng: [49.0078827, 2.5507855]
KPHX, Phoenix Sky Harbor International Airport, Phoenix, Arizona, EUA
Status: OK
OK: True
LatLng: [33.436253, -112.012159]
KCHS, Charleston International Airport, Charleston, Carolina do Sul, EUA
Status: OK
OK: True
LatLng: [32.8916648, -80.0395233]
KRIC, Richmond International Airport, Richmond, Virgínia, EUA
Status: OK
OK: True
LatLng: [37.5105562, -77.3266991]
KJAX, Jacksonville International Airport, Jacksonville, Flórida, EUA
Status: OK
OK: True
LatLng: [30.4943308, -81.68714969999999]
KORF, Norfolk International Airport, Norfolk, Virgínia, EUA
Status: OK
OK: True
LatLng: [36.8935106, -76.1993707]
KSTL, St. Louis Lambert International Airport, St. Louis, Missouri, EUA
Status: OK
OK: True
LatLng: [38.7499403, -90.374819]
KSDF, Louisville Muhammad Ali International Airport, Louisville, Kentucky, EUA
Status: OK
OK: True
LatLng: [38.1706549, -85.7307673]
KSAN, San Diego International Airport, San Diego, Califórnia, EUA
Status: OK
OK: True
LatLng: [32.7328909, -117.1897127]
KAUS, Austin–Bergstrom International Airport, Austin, Texas, EUA
Status: OK
OK: True
LatLng: [30.2142671, -97.67062589999999]
PANC, Ted Stevens Anchorage International Airport, Anchorage, Alasca, EUA
Status: OK
OK: True
LatLng: [61.1769173, -149.9905923]
LIRF, Leonardo da Vinci–Fiumicino Airport, Roma, Itália
Status: OK
OK: True
LatLng: [41.8034632, 12.2519211]
KROC, Frederick Douglass Greater Rochester International Airport, Rochester, Nova York, EUA
Status: OK
OK: True
LatLng: [43.1164111, -77.6747767]
KMSY, Louis Armstrong New Orleans International Airport, Nova Orleans, Louisiana, EUA
Status: OK
OK: True
LatLng: [29.9940319, -90.25965699999999]
CYTZ, Billy Bishop Toronto City Airport, Toronto, Ontário, Canadá
Status: OK
OK: True
LatLng: [43.6289467, -79.3944199]
KSAV, Savannah/Hilton Head International Airport, Savannah, Geórgia, EUA
Status: OK
OK: True
LatLng: [32.1294229, -81.201871]
KBGR, Bangor International Airport, Bangor, Maine, EUA
Status: OK
OK: True
LatLng: [44.8067615, -68.8272406]
KSLC, Salt Lake City International Airport, Salt Lake City, Utah, EUA
Status: OK
OK: True
LatLng: [40.7771198, -111.9813838]

,ICAO,Airport,City/Country,lat,long
0,KORD,O'Hare International Airport,"Chicago, Illinois, EUA",41.976840,-87.904750
1,KATL,Hartsfield–Jackson Atlanta International Airport,"Atlanta, Geórgia, EUA",33.632419,-84.433312
2,KBOS,Logan International Airport,"Boston, Massachusetts, EUA",42.365891,-71.017547
3,KLAX,Los Angeles International Airport,"Los Angeles, Califórnia, EUA",33.942153,-118.403605
4,KMCO,Orlando International Airport,"Orlando, Flórida, EUA",28.432216,-81.307800
5,KMIA,Miami International Airport,"Miami, Flórida, EUA",25.792350,-80.282306
6,CYYZ,Toronto Pearson International Airport,"Toronto, Ontário, Canadá",43.679834,-79.628383
7,KDFW,Dallas Fort Worth International Airport,"Dallas–Fort Worth, Texas, EUA",32.892198,-97.039123
8,KSFO,San Francisco International Airport,"San Francisco, Califórnia, EUA",37.619114,-122.381627
9,KCLT,Charlotte Douglas International Airport,"Charlotte, Carolina do Norte, EUA",35.216299,-80.953943
10,EGLL,Heathrow Airport,"Londres, Reino Unido",51.467990,-0.455047
11,KFLL,Fort Lauderdale–Hollywood International Airport,"Fort Lauderdale, Flórida, EUA",26.073173,-80.151232
12,KDEN,Denver International Airport,"Denver, Colorado, EUA",39.856349,-104.676406
13,KRDU,Raleigh–Durham International Airport,"Raleigh–Durham, Carolina do Norte, EUA",35.879768,-78.785551
14,KDCA,Ronald Reagan Washington National Airport,"Arlington (Washington, D.C.), EUA",38.853028,-77.042792
15,KBNA,Nashville International Airport,"Nashville, Tennessee, EUA",36.130819,-86.666114
16,KIAH,George Bush Intercontinental Airport,"Houston, Texas, EUA",29.993106,-95.341625
17,KDTW,Detroit Metropolitan Wayne County Airport,"Detroit, Michigan, EUA",42.213220,-83.352482
18,KIND,Indianapolis International Airport,"Indianapolis, Indiana, EUA",39.714962,-86.297705
19,KPIT,Pittsburgh International Airport,"Pittsburgh, Pensilvânia, EUA",40.492854,-80.237294
20,KPBI,Palm Beach International Airport,"West Palm Beach, Flórida, EUA",26.685748,-80.092816
21,KTPA,Tampa International Airport,"Tampa, Flórida, EUA",27.976865,-82.530280
22,KCLE,Cleveland Hopkins International Airport,"Cleveland, Ohio, EUA",41.405799,-81.853867
23,KCVG,Cincinnati/Northern Kentucky International Air...,"Hebron (Cincinnati), Kentucky, EUA",39.051351,-84.667145
24,KCMH,John Glenn Columbus International Airport,"Columbus, Ohio, EUA",39.998728,-82.884463
25,KMSP,Minneapolis–Saint Paul International Airport,"Minneapolis–Saint Paul, Minnesota, EUA",44.885059,-93.214435
26,KLAS,Harry Reid International Airport,"Las Vegas, Nevada, EUA",36.083091,-115.148224
27,KBUF,Buffalo Niagara International Airport,"Buffalo, Nova York, EUA",42.939405,-78.733501
28,TJSJ,Luis Muñoz Marín International Airport,"San Juan, Porto Rico",18.439504,-65.999228
29,KIAD,Washington Dulles International Airport,"Washington, D.C. (Virgínia), EUA",38.952248,-77.457889
30,KSEA,Seattle–Tacoma International Airport,"Seattle, Washington, EUA",47.448365,-122.308593
31,CYUL,Montréal–Trudeau International Airport,"Montreal, Québec, Canadá",45.465787,-73.745404
32,LFPG,Charles de Gaulle Airport,"Paris, França",49.007883,2.550785
33,KPHX,Phoenix Sky Harbor International Airport,"Phoenix, Arizona, EUA",33.436253,-112.012159
34,KCHS,Charleston International Airport,"Charleston, Carolina do Sul, EUA",32.891665,-80.039523
35,KRIC,Richmond International Airport,"Richmond, Virgínia, EUA",37.510556,-77.326699
36,KJAX,Jacksonville International Airport,"Jacksonville, Flórida, EUA",30.494331,-81.687150
37,KORF,Norfolk International Airport,"Norfolk, Virgínia, EUA",36.893511,-76.199371
38,KSTL,St. Louis Lambert International Airport,"St. Louis, Missouri, EUA",38.749940,-90.374819
39,KSDF,Louisville Muhammad Ali International Airport,"Louisville, Kentucky, EUA",38.170655,-85.730767
40,KSAN,San Diego International Airport,"San Diego, Califórnia, EUA",32.732891,-117.189713
41,KAUS,Austin–Bergstrom International Airport,"Austin, Texas, EUA",30.214267,-97.670626
42,PANC,Ted Stevens Anchorage International Airport,"Anchorage, Alasca, EUA",61.176917,-149.990592
43,LIRF,Leonardo da Vinci–Fiumicino Airport,"Roma, Itália",41.803463,12.251921
44,KROC,Frederick Douglass Greater Rochester Internati...,"Rochester, Nova York, EUA",43.116411,-77.674777
45,KMSY,Louis Armstrong New Orleans International Airport,"Nova Orleans, Louisiana, EUA",29.994032,-90.259657
46,CYTZ,Billy Bishop Toronto City Airport,"Toronto, Ontário, Canadá",43.628947,-79.394420
47,KSAV,Savannah/Hilton Head International Airport,"Savannah, Geórgia, EUA",32.129423,-81.201871
48,KBGR,Bangor International Airport,"Bangor, Maine, EUA",44.806762,-68.827241
49,KSLC,Salt Lake City International Airport,"Salt Lake City, Utah, EUA",40.777120,-111.981384

In [10]:
top_50_airports = top_50_airports.rename(columns={"Airport":"dep_airport",
                                "lat":"lat_dep",
                                "long": "long_dep"})
top_50_airports

,ICAO,dep_airport,City/Country,lat_dep,long_dep
0,KORD,O'Hare International Airport,"Chicago, Illinois, EUA",41.976840,-87.904750
1,KATL,Hartsfield–Jackson Atlanta International Airport,"Atlanta, Geórgia, EUA",33.632419,-84.433312
2,KBOS,Logan International Airport,"Boston, Massachusetts, EUA",42.365891,-71.017547
3,KLAX,Los Angeles International Airport,"Los Angeles, Califórnia, EUA",33.942153,-118.403605
4,KMCO,Orlando International Airport,"Orlando, Flórida, EUA",28.432216,-81.307800
5,KMIA,Miami International Airport,"Miami, Flórida, EUA",25.792350,-80.282306
6,CYYZ,Toronto Pearson International Airport,"Toronto, Ontário, Canadá",43.679834,-79.628383
7,KDFW,Dallas Fort Worth International Airport,"Dallas–Fort Worth, Texas, EUA",32.892198,-97.039123
8,KSFO,San Francisco International Airport,"San Francisco, Califórnia, EUA",37.619114,-122.381627
9,KCLT,Charlotte Douglas International Airport,"Charlotte, Carolina do Norte, EUA",35.216299,-80.953943
10,EGLL,Heathrow Airport,"Londres, Reino Unido",51.467990,-0.455047
11,KFLL,Fort Lauderdale–Hollywood International Airport,"Fort Lauderdale, Flórida, EUA",26.073173,-80.151232
12,KDEN,Denver International Airport,"Denver, Colorado, EUA",39.856349,-104.676406
13,KRDU,Raleigh–Durham International Airport,"Raleigh–Durham, Carolina do Norte, EUA",35.879768,-78.785551
14,KDCA,Ronald Reagan Washington National Airport,"Arlington (Washington, D.C.), EUA",38.853028,-77.042792
15,KBNA,Nashville International Airport,"Nashville, Tennessee, EUA",36.130819,-86.666114
16,KIAH,George Bush Intercontinental Airport,"Houston, Texas, EUA",29.993106,-95.341625
17,KDTW,Detroit Metropolitan Wayne County Airport,"Detroit, Michigan, EUA",42.213220,-83.352482
18,KIND,Indianapolis International Airport,"Indianapolis, Indiana, EUA",39.714962,-86.297705
19,KPIT,Pittsburgh International Airport,"Pittsburgh, Pensilvânia, EUA",40.492854,-80.237294
20,KPBI,Palm Beach International Airport,"West Palm Beach, Flórida, EUA",26.685748,-80.092816
21,KTPA,Tampa International Airport,"Tampa, Flórida, EUA",27.976865,-82.530280
22,KCLE,Cleveland Hopkins International Airport,"Cleveland, Ohio, EUA",41.405799,-81.853867
23,KCVG,Cincinnati/Northern Kentucky International Air...,"Hebron (Cincinnati), Kentucky, EUA",39.051351,-84.667145
24,KCMH,John Glenn Columbus International Airport,"Columbus, Ohio, EUA",39.998728,-82.884463
25,KMSP,Minneapolis–Saint Paul International Airport,"Minneapolis–Saint Paul, Minnesota, EUA",44.885059,-93.214435
26,KLAS,Harry Reid International Airport,"Las Vegas, Nevada, EUA",36.083091,-115.148224
27,KBUF,Buffalo Niagara International Airport,"Buffalo, Nova York, EUA",42.939405,-78.733501
28,TJSJ,Luis Muñoz Marín International Airport,"San Juan, Porto Rico",18.439504,-65.999228
29,KIAD,Washington Dulles International Airport,"Washington, D.C. (Virgínia), EUA",38.952248,-77.457889
30,KSEA,Seattle–Tacoma International Airport,"Seattle, Washington, EUA",47.448365,-122.308593
31,CYUL,Montréal–Trudeau International Airport,"Montreal, Québec, Canadá",45.465787,-73.745404
32,LFPG,Charles de Gaulle Airport,"Paris, França",49.007883,2.550785
33,KPHX,Phoenix Sky Harbor International Airport,"Phoenix, Arizona, EUA",33.436253,-112.012159
34,KCHS,Charleston International Airport,"Charleston, Carolina do Sul, EUA",32.891665,-80.039523
35,KRIC,Richmond International Airport,"Richmond, Virgínia, EUA",37.510556,-77.326699
36,KJAX,Jacksonville International Airport,"Jacksonville, Flórida, EUA",30.494331,-81.687150
37,KORF,Norfolk International Airport,"Norfolk, Virgínia, EUA",36.893511,-76.199371
38,KSTL,St. Louis Lambert International Airport,"St. Louis, Missouri, EUA",38.749940,-90.374819
39,KSDF,Louisville Muhammad Ali International Airport,"Louisville, Kentucky, EUA",38.170655,-85.730767
40,KSAN,San Diego International Airport,"San Diego, Califórnia, EUA",32.732891,-117.189713
41,KAUS,Austin–Bergstrom International Airport,"Austin, Texas, EUA",30.214267,-97.670626
42,PANC,Ted Stevens Anchorage International Airport,"Anchorage, Alasca, EUA",61.176917,-149.990592
43,LIRF,Leonardo da Vinci–Fiumicino Airport,"Roma, Itália",41.803463,12.251921
44,KROC,Frederick Douglass Greater Rochester Internati...,"Rochester, Nova York, EUA",43.116411,-77.674777
45,KMSY,Louis Armstrong New Orleans International Airport,"Nova Orleans, Louisiana, EUA",29.994032,-90.259657
46,CYTZ,Billy Bishop Toronto City Airport,"Toronto, Ontário, Canadá",43.628947,-79.394420
47,KSAV,Savannah/Hilton Head International Airport,"Savannah, Geórgia, EUA",32.129423,-81.201871
48,KBGR,Bangor International Airport,"Bangor, Maine, EUA",44.806762,-68.827241
49,KSLC,Salt Lake City International Airport,"Salt Lake City, Utah, EUA",40.777120,-111.981384

In [12]:
top_50_airports = top_50_airports.drop(columns=["City/Country"])
top_50_airports

,ICAO,dep_airport,lat_dep,long_dep
0,KORD,O'Hare International Airport,41.976840,-87.904750
1,KATL,Hartsfield–Jackson Atlanta International Airport,33.632419,-84.433312
2,KBOS,Logan International Airport,42.365891,-71.017547
3,KLAX,Los Angeles International Airport,33.942153,-118.403605
4,KMCO,Orlando International Airport,28.432216,-81.307800
5,KMIA,Miami International Airport,25.792350,-80.282306
6,CYYZ,Toronto Pearson International Airport,43.679834,-79.628383
7,KDFW,Dallas Fort Worth International Airport,32.892198,-97.039123
8,KSFO,San Francisco International Airport,37.619114,-122.381627
9,KCLT,Charlotte Douglas International Airport,35.216299,-80.953943
10,EGLL,Heathrow Airport,51.467990,-0.455047
11,KFLL,Fort Lauderdale–Hollywood International Airport,26.073173,-80.151232
12,KDEN,Denver International Airport,39.856349,-104.676406
13,KRDU,Raleigh–Durham International Airport,35.879768,-78.785551
14,KDCA,Ronald Reagan Washington National Airport,38.853028,-77.042792
15,KBNA,Nashville International Airport,36.130819,-86.666114
16,KIAH,George Bush Intercontinental Airport,29.993106,-95.341625
17,KDTW,Detroit Metropolitan Wayne County Airport,42.213220,-83.352482
18,KIND,Indianapolis International Airport,39.714962,-86.297705
19,KPIT,Pittsburgh International Airport,40.492854,-80.237294
20,KPBI,Palm Beach International Airport,26.685748,-80.092816
21,KTPA,Tampa International Airport,27.976865,-82.530280
22,KCLE,Cleveland Hopkins International Airport,41.405799,-81.853867
23,KCVG,Cincinnati/Northern Kentucky International Air...,39.051351,-84.667145
24,KCMH,John Glenn Columbus International Airport,39.998728,-82.884463
25,KMSP,Minneapolis–Saint Paul International Airport,44.885059,-93.214435
26,KLAS,Harry Reid International Airport,36.083091,-115.148224
27,KBUF,Buffalo Niagara International Airport,42.939405,-78.733501
28,TJSJ,Luis Muñoz Marín International Airport,18.439504,-65.999228
29,KIAD,Washington Dulles International Airport,38.952248,-77.457889
30,KSEA,Seattle–Tacoma International Airport,47.448365,-122.308593
31,CYUL,Montréal–Trudeau International Airport,45.465787,-73.745404
32,LFPG,Charles de Gaulle Airport,49.007883,2.550785
33,KPHX,Phoenix Sky Harbor International Airport,33.436253,-112.012159
34,KCHS,Charleston International Airport,32.891665,-80.039523
35,KRIC,Richmond International Airport,37.510556,-77.326699
36,KJAX,Jacksonville International Airport,30.494331,-81.687150
37,KORF,Norfolk International Airport,36.893511,-76.199371
38,KSTL,St. Louis Lambert International Airport,38.749940,-90.374819
39,KSDF,Louisville Muhammad Ali International Airport,38.170655,-85.730767
40,KSAN,San Diego International Airport,32.732891,-117.189713
41,KAUS,Austin–Bergstrom International Airport,30.214267,-97.670626
42,PANC,Ted Stevens Anchorage International Airport,61.176917,-149.990592
43,LIRF,Leonardo da Vinci–Fiumicino Airport,41.803463,12.251921
44,KROC,Frederick Douglass Greater Rochester Internati...,43.116411,-77.674777
45,KMSY,Louis Armstrong New Orleans International Airport,29.994032,-90.259657
46,CYTZ,Billy Bishop Toronto City Airport,43.628947,-79.394420
47,KSAV,Savannah/Hilton Head International Airport,32.129423,-81.201871
48,KBGR,Bangor International Airport,44.806762,-68.827241
49,KSLC,Salt Lake City International Airport,40.777120,-111.981384

In [13]:
top_50_airports["arrival"] = "New York"

In [15]:
top_50_airports.head(5)

,ICAO,dep_airport,lat_dep,long_dep,arrival
0,KORD,O'Hare International Airport,41.976840,-87.904750,New York
1,KATL,Hartsfield–Jackson Atlanta International Airport,33.632419,-84.433312,New York
2,KBOS,Logan International Airport,42.365891,-71.017547,New York
3,KLAX,Los Angeles International Airport,33.942153,-118.403605,New York
4,KMCO,Orlando International Airport,28.432216,-81.307800,New York

In [16]:
top_50_airports ["lat_ny"] = 40.7128

In [17]:
top_50_airports ["long_ny"] = -74.0060

In [18]:
top_50_airports.head(5)

,ICAO,dep_airport,lat_dep,long_dep,arrival,lat_ny,long_ny
0,KORD,O'Hare International Airport,41.976840,-87.904750,New York,40.7128,-74.006
1,KATL,Hartsfield–Jackson Atlanta International Airport,33.632419,-84.433312,New York,40.7128,-74.006
2,KBOS,Logan International Airport,42.365891,-71.017547,New York,40.7128,-74.006
3,KLAX,Los Angeles International Airport,33.942153,-118.403605,New York,40.7128,-74.006
4,KMCO,Orlando International Airport,28.432216,-81.307800,New York,40.7128,-74.006

In [19]:
top_50_airports.to_csv("top50_airports.csv", index=False)