In [1]:
import pandas as pd

## 2025

In [2]:
#2025
lga_2025 = pd.read_csv('laguardia_2025.csv')
lga_2025.head(5)

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,a07579,1.749261e+09,KMCO,1749268709,KLGA,DAL2520,9751.0,610.0,434,16,0,3
1,aa0759,1.749266e+09,KIAD,1749268625,KLGA,RPA3413,500.0,11.0,601,24,2,3
2,a042db,1.749258e+09,KDFW,1749268499,KLGA,DAL846,1628.0,279.0,407,8,2,3
3,a44cfd,1.749260e+09,KTPA,1749268354,KLGA,DAL2404,1541.0,30.0,385,8,1,3
4,a3a8ef,1.749262e+09,KATL,1749268209,KLGA,FFT3288,1731.0,15.0,362,8,0,3

In [3]:
lga_2025.shape

(14516, 12)

In [4]:
jfk_2025 = pd.read_csv('jfk_2025.csv')
jfk_2025.head(5)

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,a85ff5,1.749260e+09,KMCO,1749268639,KJFK,JBU884,8870.0,740.0,1882,18,0,1
1,a66ce0,1.749252e+09,KSEA,1749268421,KJFK,DAL1274,979.0,66.0,1719,18,2,1
2,ab43c6,1.749260e+09,KTPA,1749268314,KJFK,DAL2565,909.0,23.0,1508,3,2,1
3,a6d83c,1.749253e+09,KLAS,1749268237,KJFK,DAL807,1957.0,1.0,1692,18,1,1
4,a657bf,1.749263e+09,KCLT,1749268126,KJFK,AAL1727,2780.0,305.0,1621,11,0,1

In [5]:
jfk_2025.shape

(20162, 12)

In [6]:
newark_2025 = pd.read_csv('df_newark_2025.csv')
newark_2025.head(5)

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,a36636,1.749260e+09,KMIA,1749268729,KEWR,AAL2008,2196.0,96.0,1054,40,1,5
1,a29212,1.749266e+09,KBOS,1749268551,KEWR,FDX3926,804.0,16.0,1095,40,0,5
2,adf194,1.749263e+09,KCLT,1749268343,KEWR,AAL2794,4062.0,373.0,1102,40,0,5
3,ac7f3e,1.749253e+09,KLAS,1749268224,KEWR,NKS2487,539.0,59.0,1108,47,1,5
4,aa03a2,1.749265e+09,KCLE,1749268132,KEWR,RPA3431,571.0,208.0,832,32,3,5

In [7]:
newark_2025.shape

(16922, 12)

In [8]:
df_2025 = pd.concat([jfk_2025, lga_2025, newark_2025], ignore_index=True)
df_2025

,icao24,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign,estDepartureAirportHorizDistance,estDepartureAirportVertDistance,estArrivalAirportHorizDistance,estArrivalAirportVertDistance,departureAirportCandidatesCount,arrivalAirportCandidatesCount
0,a85ff5,1.749260e+09,KMCO,1749268639,KJFK,JBU884,8870.0,740.0,1882,18,0,1
1,a66ce0,1.749252e+09,KSEA,1749268421,KJFK,DAL1274,979.0,66.0,1719,18,2,1
2,ab43c6,1.749260e+09,KTPA,1749268314,KJFK,DAL2565,909.0,23.0,1508,3,2,1
3,a6d83c,1.749253e+09,KLAS,1749268237,KJFK,DAL807,1957.0,1.0,1692,18,1,1
4,a657bf,1.749263e+09,KCLT,1749268126,KJFK,AAL1727,2780.0,305.0,1621,11,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
51595,a880ff,1.751685e+09,KORD,1751690579,KEWR,UAL3914,1092.0,37.0,1290,51,0,5
51596,a3813b,1.751684e+09,KATL,1751689965,KEWR,DAL2552,3230.0,388.0,362,66,0,5
51597,ab7da4,1.751687e+09,KFRG,1751689807,KEWR,N84BL,606.0,5.0,5614,35,0,5
51598,a3e55a,1.751684e+09,KATL,1751689685,KEWR,FFT4602,1603.0,258.0,866,66,1,5
51599,a2452f,1.751676e+09,KDEN,1751688895,KEWR,UAL2613,3997.0,81.0,658,58,2,5

In [9]:
df_2025 = df_2025.drop(columns = ["icao24", "estDepartureAirportHorizDistance", "estDepartureAirportVertDistance", "estArrivalAirportHorizDistance", "estArrivalAirportVertDistance", "departureAirportCandidatesCount", "arrivalAirportCandidatesCount"])

In [10]:
df_2025

,firstSeen,estDepartureAirport,lastSeen,estArrivalAirport,callsign
0,1.749260e+09,KMCO,1749268639,KJFK,JBU884
1,1.749252e+09,KSEA,1749268421,KJFK,DAL1274
2,1.749260e+09,KTPA,1749268314,KJFK,DAL2565
3,1.749253e+09,KLAS,1749268237,KJFK,DAL807
4,1.749263e+09,KCLT,1749268126,KJFK,AAL1727
...,...,...,...,...,...
51595,1.751685e+09,KORD,1751690579,KEWR,UAL3914
51596,1.751684e+09,KATL,1751689965,KEWR,DAL2552
51597,1.751687e+09,KFRG,1751689807,KEWR,N84BL
51598,1.751684e+09,KATL,1751689685,KEWR,FFT4602
51599,1.751676e+09,KDEN,1751688895,KEWR,UAL2613

In [11]:
df_2025 = df_2025.rename(columns = {"firstSeen" : "departure_time",
                               "estDepartureAirport" : "departure_airport", 
                               "lastSeen" : "arrival_time",
                               "estArrivalAirport" : "arrival_airport"})
df_2025

,departure_time,departure_airport,arrival_time,arrival_airport,callsign
0,1.749260e+09,KMCO,1749268639,KJFK,JBU884
1,1.749252e+09,KSEA,1749268421,KJFK,DAL1274
2,1.749260e+09,KTPA,1749268314,KJFK,DAL2565
3,1.749253e+09,KLAS,1749268237,KJFK,DAL807
4,1.749263e+09,KCLT,1749268126,KJFK,AAL1727
...,...,...,...,...,...
51595,1.751685e+09,KORD,1751690579,KEWR,UAL3914
51596,1.751684e+09,KATL,1751689965,KEWR,DAL2552
51597,1.751687e+09,KFRG,1751689807,KEWR,N84BL
51598,1.751684e+09,KATL,1751689685,KEWR,FFT4602
51599,1.751676e+09,KDEN,1751688895,KEWR,UAL2613

In [12]:
df_2025["arrival_time_converted"] = (
    pd.to_datetime(df_2025["arrival_time"], unit="s", utc=True) #unit = s says that is in seconds
    .dt.tz_convert("America/New_York") #converts to ny timezone                       
    .dt.strftime("%Y-%m-%d %H:%M")
)

In [13]:
df_2025

,departure_time,departure_airport,arrival_time,arrival_airport,callsign,arrival_time_converted
0,1.749260e+09,KMCO,1749268639,KJFK,JBU884,2025-06-06 23:57
1,1.749252e+09,KSEA,1749268421,KJFK,DAL1274,2025-06-06 23:53
2,1.749260e+09,KTPA,1749268314,KJFK,DAL2565,2025-06-06 23:51
3,1.749253e+09,KLAS,1749268237,KJFK,DAL807,2025-06-06 23:50
4,1.749263e+09,KCLT,1749268126,KJFK,AAL1727,2025-06-06 23:48
...,...,...,...,...,...,...
51595,1.751685e+09,KORD,1751690579,KEWR,UAL3914,2025-07-05 00:42
51596,1.751684e+09,KATL,1751689965,KEWR,DAL2552,2025-07-05 00:32
51597,1.751687e+09,KFRG,1751689807,KEWR,N84BL,2025-07-05 00:30
51598,1.751684e+09,KATL,1751689685,KEWR,FFT4602,2025-07-05 00:28
51599,1.751676e+09,KDEN,1751688895,KEWR,UAL2613,2025-07-05 00:14

In [14]:
#converting departure time
df_2025["departure_time_converted"] = (
    pd.to_datetime(df_2025["departure_time"], unit="s", utc=True) #unit = s says that is in seconds
    .dt.tz_convert("America/New_York") #converts to ny timezone                       
    .dt.strftime("%Y-%m-%d %H:%M")
)

In [15]:
df_2025

,departure_time,departure_airport,arrival_time,arrival_airport,callsign,arrival_time_converted,departure_time_converted
0,1.749260e+09,KMCO,1749268639,KJFK,JBU884,2025-06-06 23:57,2025-06-06 21:27
1,1.749252e+09,KSEA,1749268421,KJFK,DAL1274,2025-06-06 23:53,2025-06-06 19:17
2,1.749260e+09,KTPA,1749268314,KJFK,DAL2565,2025-06-06 23:51,2025-06-06 21:26
3,1.749253e+09,KLAS,1749268237,KJFK,DAL807,2025-06-06 23:50,2025-06-06 19:30
4,1.749263e+09,KCLT,1749268126,KJFK,AAL1727,2025-06-06 23:48,2025-06-06 22:23
...,...,...,...,...,...,...,...
51595,1.751685e+09,KORD,1751690579,KEWR,UAL3914,2025-07-05 00:42,2025-07-04 23:10
51596,1.751684e+09,KATL,1751689965,KEWR,DAL2552,2025-07-05 00:32,2025-07-04 22:53
51597,1.751687e+09,KFRG,1751689807,KEWR,N84BL,2025-07-05 00:30,2025-07-04 23:46
51598,1.751684e+09,KATL,1751689685,KEWR,FFT4602,2025-07-05 00:28,2025-07-04 22:49
51599,1.751676e+09,KDEN,1751688895,KEWR,UAL2613,2025-07-05 00:14,2025-07-04 20:44

In [16]:
df_2025[["arrival", "time"]] = df_2025["arrival_time_converted"].str.split(" ", expand=True)

In [17]:
df_2025

,departure_time,departure_airport,arrival_time,arrival_airport,callsign,arrival_time_converted,departure_time_converted,arrival,time
0,1.749260e+09,KMCO,1749268639,KJFK,JBU884,2025-06-06 23:57,2025-06-06 21:27,2025-06-06,23:57
1,1.749252e+09,KSEA,1749268421,KJFK,DAL1274,2025-06-06 23:53,2025-06-06 19:17,2025-06-06,23:53
2,1.749260e+09,KTPA,1749268314,KJFK,DAL2565,2025-06-06 23:51,2025-06-06 21:26,2025-06-06,23:51
3,1.749253e+09,KLAS,1749268237,KJFK,DAL807,2025-06-06 23:50,2025-06-06 19:30,2025-06-06,23:50
4,1.749263e+09,KCLT,1749268126,KJFK,AAL1727,2025-06-06 23:48,2025-06-06 22:23,2025-06-06,23:48
...,...,...,...,...,...,...,...,...,...
51595,1.751685e+09,KORD,1751690579,KEWR,UAL3914,2025-07-05 00:42,2025-07-04 23:10,2025-07-05,00:42
51596,1.751684e+09,KATL,1751689965,KEWR,DAL2552,2025-07-05 00:32,2025-07-04 22:53,2025-07-05,00:32
51597,1.751687e+09,KFRG,1751689807,KEWR,N84BL,2025-07-05 00:30,2025-07-04 23:46,2025-07-05,00:30
51598,1.751684e+09,KATL,1751689685,KEWR,FFT4602,2025-07-05 00:28,2025-07-04 22:49,2025-07-05,00:28
51599,1.751676e+09,KDEN,1751688895,KEWR,UAL2613,2025-07-05 00:14,2025-07-04 20:44,2025-07-05,00:14

In [18]:
df_2025 = df_2025.rename(columns={"departure_time": "dep_unix",
                            "arrival_time" : "arrival_unix",
                             "departure_time_converted" : "dep_conv",
                             "arrival_time_converted" : "arrival_conv",
                                  "departure_airport" : "dep_airport",
                                  "arrival_airport" : "arr_airport"})
df_2025

,dep_unix,dep_airport,arrival_unix,arr_airport,callsign,arrival_conv,dep_conv,arrival,time
0,1.749260e+09,KMCO,1749268639,KJFK,JBU884,2025-06-06 23:57,2025-06-06 21:27,2025-06-06,23:57
1,1.749252e+09,KSEA,1749268421,KJFK,DAL1274,2025-06-06 23:53,2025-06-06 19:17,2025-06-06,23:53
2,1.749260e+09,KTPA,1749268314,KJFK,DAL2565,2025-06-06 23:51,2025-06-06 21:26,2025-06-06,23:51
3,1.749253e+09,KLAS,1749268237,KJFK,DAL807,2025-06-06 23:50,2025-06-06 19:30,2025-06-06,23:50
4,1.749263e+09,KCLT,1749268126,KJFK,AAL1727,2025-06-06 23:48,2025-06-06 22:23,2025-06-06,23:48
...,...,...,...,...,...,...,...,...,...
51595,1.751685e+09,KORD,1751690579,KEWR,UAL3914,2025-07-05 00:42,2025-07-04 23:10,2025-07-05,00:42
51596,1.751684e+09,KATL,1751689965,KEWR,DAL2552,2025-07-05 00:32,2025-07-04 22:53,2025-07-05,00:32
51597,1.751687e+09,KFRG,1751689807,KEWR,N84BL,2025-07-05 00:30,2025-07-04 23:46,2025-07-05,00:30
51598,1.751684e+09,KATL,1751689685,KEWR,FFT4602,2025-07-05 00:28,2025-07-04 22:49,2025-07-05,00:28
51599,1.751676e+09,KDEN,1751688895,KEWR,UAL2613,2025-07-05 00:14,2025-07-04 20:44,2025-07-05,00:14

In [19]:
df_2025 = df_2025[["dep_unix", "dep_conv", "dep_airport", "callsign", "arr_airport", "arrival_unix", "arrival_conv", "arrival", "time"]]

In [20]:
df_2025

,dep_unix,dep_conv,dep_airport,callsign,arr_airport,arrival_unix,arrival_conv,arrival,time
0,1.749260e+09,2025-06-06 21:27,KMCO,JBU884,KJFK,1749268639,2025-06-06 23:57,2025-06-06,23:57
1,1.749252e+09,2025-06-06 19:17,KSEA,DAL1274,KJFK,1749268421,2025-06-06 23:53,2025-06-06,23:53
2,1.749260e+09,2025-06-06 21:26,KTPA,DAL2565,KJFK,1749268314,2025-06-06 23:51,2025-06-06,23:51
3,1.749253e+09,2025-06-06 19:30,KLAS,DAL807,KJFK,1749268237,2025-06-06 23:50,2025-06-06,23:50
4,1.749263e+09,2025-06-06 22:23,KCLT,AAL1727,KJFK,1749268126,2025-06-06 23:48,2025-06-06,23:48
...,...,...,...,...,...,...,...,...,...
51595,1.751685e+09,2025-07-04 23:10,KORD,UAL3914,KEWR,1751690579,2025-07-05 00:42,2025-07-05,00:42
51596,1.751684e+09,2025-07-04 22:53,KATL,DAL2552,KEWR,1751689965,2025-07-05 00:32,2025-07-05,00:32
51597,1.751687e+09,2025-07-04 23:46,KFRG,N84BL,KEWR,1751689807,2025-07-05 00:30,2025-07-05,00:30
51598,1.751684e+09,2025-07-04 22:49,KATL,FFT4602,KEWR,1751689685,2025-07-05 00:28,2025-07-05,00:28
51599,1.751676e+09,2025-07-04 20:44,KDEN,UAL2613,KEWR,1751688895,2025-07-05 00:14,2025-07-05,00:14

In [27]:
df_2025 = df_2025[~((df_2025["arr_airport"] == "KEWR") & (df_2025["dep_airport"] == "KEWR"))]

In [28]:
df_2025.shape

(50352, 9)

In [31]:
df_2025 = df_2025[~((df_2025["arr_airport"] == "KJFK") & (df_2025["dep_airport"] == "KJFK"))]

In [32]:
df_2025.shape

(49808, 9)

In [34]:
df_2025 = df_2025[~((df_2025["arr_airport"] == "KLGA") & (df_2025["dep_airport"] == "KLGA"))]

In [35]:
df_2025.shape

(49792, 9)

In [37]:
df_2025 = df_2025[~((df_2025["arr_airport"] == "KLGA") & (df_2025["dep_airport"] == "KJFK"))]

In [38]:
df_2025.shape

(49767, 9)

In [39]:
df_2025[(df_2025["arr_airport"] == "KLGA") & (df_2025["dep_airport"] == "KWER")]

Empty DataFrame
Columns: [dep_unix, dep_conv, dep_airport, callsign, arr_airport, arrival_unix, arrival_conv, arrival, time]
Index: []

In [40]:
df_2025[(df_2025["arr_airport"] == "KJFK") & (df_2025["dep_airport"] == "KWER")]

Empty DataFrame
Columns: [dep_unix, dep_conv, dep_airport, callsign, arr_airport, arrival_unix, arrival_conv, arrival, time]
Index: []

In [42]:
df_2025 = df_2025[~((df_2025["arr_airport"] == "KJFK") & (df_2025["dep_airport"] == "KLGA"))]

In [43]:
df_2025.shape

(49757, 9)

In [44]:
df_2025[(df_2025["arr_airport"] == "KWER") & (df_2025["dep_airport"] == "KJFK")]

Empty DataFrame
Columns: [dep_unix, dep_conv, dep_airport, callsign, arr_airport, arrival_unix, arrival_conv, arrival, time]
Index: []

In [45]:
df_2025.to_csv("df_2025.csv", index=False)

In [22]:
df_2025.groupby("arr_airport")["arrival"].count()

arr_airport
KEWR    16922
KJFK    20162
KLGA    14516
Name: arrival, dtype: int64

In [46]:
arrivals_2025 = df_2025.groupby("arrival")["arr_airport"].count()
arrivals_2025

arrival
2025-06-06    1549
2025-06-07    1437
2025-06-08    1627
2025-06-09    1659
2025-06-10    1668
2025-06-11    1719
2025-06-12    1763
2025-06-13    1754
2025-06-14    1477
2025-06-15    1628
2025-06-16    1729
2025-06-17    1694
2025-06-18    1683
2025-06-19    1519
2025-06-20    1852
2025-06-21    1506
2025-06-22    1690
2025-06-23    1824
2025-06-24    1790
2025-06-25    1690
2025-06-26    1688
2025-06-27    1767
2025-06-28    1521
2025-06-29    1754
2025-06-30    1563
2025-07-01    1429
2025-07-02    1877
2025-07-03    1573
2025-07-04    1780
2025-07-05    1547
Name: arr_airport, dtype: int64

In [47]:
arrivals_2025.describe()

count      30.000000
mean     1658.566667
std       122.906099
min      1429.000000
25%      1552.500000
50%      1685.500000
75%      1754.000000
max      1877.000000
Name: arr_airport, dtype: float64

In [48]:
arrivals_2025.to_csv("arrivals_2025.csv")

In [26]:
df_2025["dep_airport"].value_counts().sort_values(ascending=False).head(50)

dep_airport
KORD    1662
KATL    1396
KLAX    1333
KBOS    1322
KEWR    1313
KMCO    1225
CYYZ    1195
KMIA    1152
KCLT    1040
KDFW    1040
KSFO     938
EGLL     926
KRDU     888
KFLL     867
KDEN     802
KDCA     743
KDTW     707
KBNA     697
KIAH     658
KJFK     628
KTPA     624
KPIT     596
KCVG     572
KIND     563
TJSJ     551
CYUL     527
KLAS     518
KCMH     508
KMSP     506
KPBI     506
KCLE     504
KBUF     476
KIAD     470
LFPG     460
KSEA     445
KRIC     418
KORF     381
KCHS     381
KPHX     381
KSTL     371
KPWM     351
KJAX     333
KSDF     333
KSAN     332
KAUS     307
PANC     304
LIRF     288
KSAV     284
KROC     281
KMSY     280
Name: count, dtype: int64

## graphs

In [30]:
df_geo = pd.read_csv("df_geo.csv")
df_geo

,Venue,City,Country,lat,long
0,New York New Jersey Stadium,New York/New Jersey,United States,40.813506,-74.074457
1,Kansas City Stadium,Kansas City,United States,39.048965,-94.484014
2,San Francisco Bay Area Stadium,San Francisco Bay Area,United States,37.403317,-121.969377
3,Atlanta Stadium,Atlanta,United States,33.755323,-84.400590
4,Miami Stadium,Miami,United States,25.761680,-80.191790
5,Houston Stadium,Houston,United States,29.684722,-95.410707
6,Dallas Stadium,Dallas,United States,32.748028,-97.092812
7,Los Angeles Stadium,Los Angeles,United States,33.953477,-118.339023
8,Philadelphia Stadium,Philadelphia,United States,39.901419,-75.167599
9,Boston Stadium,Boston,United States,42.090927,-71.264363
10,Seattle Stadium,Seattle,United States,47.595152,-122.331639
11,BC Place Vancouver,Vancouver,Canada,49.282729,-123.120738
12,Toronto Stadium,Toronto,Canada,43.633195,-79.418563
13,Mexico City Stadium,Mexico City,Mexico,19.302861,-99.150528
14,Monterrey Stadium,Monterrey,Mexico,25.669151,-100.244443
15,Guadalajara Stadium,Guadalajara,Mexico,20.681776,-103.462645

In [31]:
matches_by_stadium = pd.read_csv("matches_by_stadium.csv")
matches_by_stadium

                                      Venue  count
0                            Dallas Stadium      9
1                       Los Angeles Stadium      8
2               New York New Jersey Stadium      8
3                           Atlanta Stadium      8
4                             Miami Stadium      8
5                            Boston Stadium      7
6                        BC Place Vancouver      7
7                       Mexico City Stadium      6
8            San Francisco Bay Area Stadium      6
9                           Houston Stadium      6
10                     Philadelphia Stadium      6
11                          Seattle Stadium      6
12                      Kansas City Stadium      6
13                          Toronto Stadium      5
14                      Estadio Guadalajara      4
15                        Estadio Monterrey      4
16     ROUND OF 32 (June 28 – July 3, 2026)      1
17      ROUND OF 16 (July 4 – July 7, 2026)      1
18  QUARTER-FINALS (July 9 – July 11, 2026)      1
19    SEMI-FINALS (July 14 – July 15, 2026)      1
20        THIRD-PLACE MATCH (July 18, 2026)      1
21                    FINAL (July 19, 2026)      1

In [36]:
matches_by_stadium = matches_by_stadium[0:16]

In [37]:
matches_by_stadium

                             Venue  count
0                   Dallas Stadium      9
1              Los Angeles Stadium      8
2      New York New Jersey Stadium      8
3                  Atlanta Stadium      8
4                    Miami Stadium      8
5                   Boston Stadium      7
6               BC Place Vancouver      7
7              Mexico City Stadium      6
8   San Francisco Bay Area Stadium      6
9                  Houston Stadium      6
10            Philadelphia Stadium      6
11                 Seattle Stadium      6
12             Kansas City Stadium      6
13                 Toronto Stadium      5
14             Estadio Guadalajara      4
15               Estadio Monterrey      4

In [38]:
matches_by_stadium["Venue"] = matches_by_stadium["Venue"].replace({
    "Estadio Guadalajara": "Guadalajara Stadium",
    "Estadio Monterrey": "Monterrey Stadium"
})

In [39]:
matches_by_stadium

                             Venue  count
0                   Dallas Stadium      9
1              Los Angeles Stadium      8
2      New York New Jersey Stadium      8
3                  Atlanta Stadium      8
4                    Miami Stadium      8
5                   Boston Stadium      7
6               BC Place Vancouver      7
7              Mexico City Stadium      6
8   San Francisco Bay Area Stadium      6
9                  Houston Stadium      6
10            Philadelphia Stadium      6
11                 Seattle Stadium      6
12             Kansas City Stadium      6
13                 Toronto Stadium      5
14             Guadalajara Stadium      4
15               Monterrey Stadium      4

In [40]:
stadiums = df_geo.merge(matches_by_stadium, on="Venue")

In [41]:
stadiums

,Venue,City,Country,lat,long,count
0,New York New Jersey Stadium,New York/New Jersey,United States,40.813506,-74.074457,8
1,Kansas City Stadium,Kansas City,United States,39.048965,-94.484014,6
2,San Francisco Bay Area Stadium,San Francisco Bay Area,United States,37.403317,-121.969377,6
3,Atlanta Stadium,Atlanta,United States,33.755323,-84.400590,8
4,Miami Stadium,Miami,United States,25.761680,-80.191790,8
5,Houston Stadium,Houston,United States,29.684722,-95.410707,6
6,Dallas Stadium,Dallas,United States,32.748028,-97.092812,9
7,Los Angeles Stadium,Los Angeles,United States,33.953477,-118.339023,8
8,Philadelphia Stadium,Philadelphia,United States,39.901419,-75.167599,6
9,Boston Stadium,Boston,United States,42.090927,-71.264363,7
10,Seattle Stadium,Seattle,United States,47.595152,-122.331639,6
11,BC Place Vancouver,Vancouver,Canada,49.282729,-123.120738,7
12,Toronto Stadium,Toronto,Canada,43.633195,-79.418563,5
13,Mexico City Stadium,Mexico City,Mexico,19.302861,-99.150528,6
14,Monterrey Stadium,Monterrey,Mexico,25.669151,-100.244443,4
15,Guadalajara Stadium,Guadalajara,Mexico,20.681776,-103.462645,4

In [42]:
stadiums.to_csv("stadiums.csv", index=False)